### PR TITLE
Add Help on Import by CSV page using the pop-up option

### PR DESCRIPTION
**Pull request by suelaP**

### CODE REVIEW

**Comment by samtuke** [comment]
Please link to the related mantis issue on mantis.phplist.com.

**Comment by mariez** [comment]
Hi Suela!
I had test your commit in my local instalation. I have this observations.

1- there is a second #globalhelp div added to the upload input section. I think this is wrong. Beside the open/close function is not working in Dressprow, you should not have in same html 2 divs whith same id.
The #globalhelp div as his name describe is for add a general help at the top of each page. All pages html already have included a div with id #globalhelp. If you want to add or modify the information inside that div, you have to commit to the respository: https://github.com/phpList/phplist-lan-info. To this page you should modify the file: https://github.com/phpList/phplist-lan-info/blob/master/en/import2.php
If you want to add information just to this particulary input file object, you should use the pop-up help object, like you did in the rest of the page.
Or, if you need a different object, because none of this are good for your need, we should develope it.

2- The pop-up helps buttons don't have the corresponding file in the help repository: https://github.com/phpList/phplist-lan-help. Each button has the correct parameter "topic" but the value must be equal to the name of the file that will popup when you click that button. That file must be uploaded to the repository phplist-lan-help and, as I can see in other cases, the name must be all lowercase.

**Comment by suelaP** [comment]
Hi Marie, 
Yes you are right on both your observations. I did not notice there was a div with the same id in that page, and I did not tests it on Dressprow. I have removed that element from the page and I have left that section as it was, in plane text. Although I think it would look better if we developed a similar object to globalhelp to put this kind of information that include lots of text. 
As for your second observation, you are totally right I have now pushed the files I created and their names are all lowercase.

**Comment by mariez** [comment]
@michield or @samtuke  can you merge this PR? https://github.com/phpList/phplist-lan-help/pull/8

**Comment by mariez** [comment]
@suelaP  I think the best way to do this is using the php Help function, as I explain to you in the email with subject 'Help icon on "View Opens" page', that way if we decide to change this icon in the future we just have to change the Help function, instead of all html.

**Comment by mariez** [comment]
For example:
To add the help button with topic testoutput, you wrote this html line 
`<a href="help/?topic=testoutput" class="helpdialog" target="_blank"><span class="glyphicon glyphicon-question-sign text-warning"></span></a>`

but you only need to write this php line:
`<?php echo help('testoutput'); ?>`

**Comment by suelaP** [comment]
Hi Marie, thats's done now, thanks for the explenation :)

**Pull request merged**
