### PR TITLE
Added intro message to maillog processing email

### PR DESCRIPTION
**Pull request by samtuke**
Also clarified two system mail subjects ("Maillist Processing info" -> "Subscriber list processing log") and added comments

### CODE REVIEW

**Comment by bramley** [comment]
The new subject sounds a bit unclear. This email is a report of processing the queue, so the subject should be something like "Queue processing report" regardless of including errors or info.

Similarly "The following events occured during the processing of a subscriber list" should refer to processing the message queue.

**Comment by samtuke** [comment]
@bramley Good point, I've now updated those messages. Better?

**Comment by bramley** [comment]
Sorry to appear to be picky, but elsewhere the process is called "sending the queue" or "sending the message queue", not "the email queue".

**Comment by michield** [comment]
yes, email is a term to avoid, as it can mean both message and address

**Comment by samtuke** [comment]
How about "Message queue processing report"? I feel "queue processing report" might be ambiguous (it could refer to an authorisation or installation queue, or something else).

**Comment by michield** [comment]
+1

**Comment by samtuke** [comment]
Now updated and ready for merge

**Comment by michield** [comment]
there's a typo in procesing

**Comment by samtuke** [comment]
Fixed - thanks!

**Pull request merged**
