### PR TITLE
Release 3.3.4

### PR DESCRIPTION
**Pull request by michield**
Merge 3.3.4 back to master

### CODE REVIEW

**Comment by xh3n1** [comment]
@michield is this ready for merge?

**Comment by michield** [comment]
Yes, @xh3n1 if you agree this has all the changes from 3.3.4 we can merge.

**Comment by samtuke** [comment]
What's the advantage of merging the release branch back into master before the final release is issued? The release procedure includes this merge, as documented in the internal wiki.

**Comment by xh3n1** [comment]
@samtuke not before the final release, but just wanted to make sure that everything is included.

**Pull request merged**
