### PR TITLE
Increase column size (admin table) on DB

### PR DESCRIPTION
**Pull request by aulona1**
Increase 'loginname' max chars to 66 on admin table.

## Description

The following changes are being made in order to solve the issue> `loginname` character limit , related to SSO plugin.

## Related Issue
The discussion can be found here https://github.com/phpList/phplist-plugin-simplesaml/issues/2

### CODE REVIEW

**Comment by michield** [comment]
Thanks. Can you also add the commit to change the table for existing installations. You'll need to change "upgrade.php"

**Review by michield — APPROVED** [review]

**Comment by bramley** [comment]
Shouldn't this test be against the **_next_** version? Otherwise someone upgrading from 3.6.7 isn't going to have this change applied.

    if (version_compare($dbversion, '3.6.7','<')) {

**Comment by michield** [comment]
> Shouldn't this test be against the **_next_** version? Otherwise someone upgrading from 3.6.7 isn't going to have this change applied.
> 
> ```
> if (version_compare($dbversion, '3.6.7','<')) {
> ```

Ah, yes, good point. @aulona1 can you update it to 3.6.8?

**Comment by bramley** [comment]
Also the sql to update the table is invalid. When CHANGE COLUMN is used, the column name needs to appear twice and the column definition needs to be repeated.  Also "default" on its own is invalid.

    alter table {$GLOBALS['tables']['admin']} change column loginname varchar(66) default 

To change only a column's definition MODIFY is simpler to use

    alter table {$GLOBALS['tables']['admin']} modify loginname  varchar(66) not null;

**Comment by michield** [comment]
Ah, yes, thanks @bramley

**Comment by aulona1** [comment]
> Also the sql to update the table is invalid. When CHANGE COLUMN is used, the column name needs to appear twice and the column definition needs to be repeated. Also "default" on its own is invalid.
> 
> ```
> alter table {$GLOBALS['tables']['admin']} change column loginname varchar(66) default 
> ```
> 
> To change only a column's definition MODIFY is simpler to use
> 
> ```
> alter table {$GLOBALS['tables']['admin']} modify loginname  varchar(66) not null;
> ```

Thanks for your insights @bramley .  
Could you please review the referred changes when your time allows?

**Comment by bramley** [comment]
@aulona1 Yes, that looks better.

**Comment by bramley** [comment]
@aulona1 Yes, that looks better.

**Review by michield — APPROVED** [review]

**Pull request merged**
