### PR TITLE
0019033: Provide default attribute for required attribute: consent to terms of service

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=19033

### CODE REVIEW

**Comment by xh3n1** [comment]
screenshot from 2018-05-03 23-14-16

**Comment by michield** [comment]
@samtuke I think this is fine, but we should make it optional to add it. For starters, it is going to break the Ajax subscribe system, but also, eventually GDPR compliance is a European problem. Europe is only a small part of the world. I think we make this optional, point all Europeans to how to switch it on, in a blog post and then we're off the hook.

**Comment by michield** [comment]
by the way, it may be optional already, so ignore me if that's the case :-)

**Comment by samtuke** [comment]
@xh3n1 This looks great. Is there a way to link to another page which would contain the Terms of Service? Perhaps there is a workaround that would make it easy for the admin to change where the link points to. It is likely admins will have TOS pages on their own website or elsewhere. If linking to such a page is difficult, then an alternative would be to store a copy of them in phpList, but I think it is better to avoid that (to avoid duplication etc.).

**Comment by xh3n1** [comment]
@samtuke It's difficult, but I will try to find a way.

**Comment by samtuke** [comment]
@x3hn1 So long as it is clear what the terms of service being referred to are (or where they can be found) then it should be OK. How about you use the domain config value in the printed statement, like "...agree to the terms of hostwebsite.com...", so that it is the responsibility of the admin of the tld on which the installation is hosted?

If we took that approach then I think we'd need to ask the community for feedback on whether it would fit their model. For example there are many generic hosting providers which make phpList accessible on domains like samsaccount.phplist.hostingcompany.com - in such cases maybe using the domain as suggested wouldn't be ideal. But it would be better than not specifying any terms at all.

**Comment by samtuke** [comment]
@xh3n1 This raises the question of whether `domain` is always set. There doesn't seem to be a convenient place to state that this config option should be accurate when choosing to load the attribute from defaults.

**Comment by maltfield** [comment]
FYI, I filed a mantis issue requesting the ability to add an html anchor link (for pointing to the ToS doc) to the text of this new default attribute:

 * https://mantis.phplist.org/view.php?id=19436

**Pull request merged**
