### PR TITLE
Use the original From address when forwarding a campaign email

### PR DESCRIPTION
**Pull request by bramley**
## Description

When forwarding a campaign email the From address is the subscriber's address not the original From address. This can cause delivery problems when using services such as Amazon SES that require the From address to be verified.

There are two changes affecting forwarding a campaign email

- Use the original From address instead of the subscriber address for the From address
- Use the subscriber address for the Reply-to address

## Related Issue

https://mantis.phplist.org/view.php?id=18075

### CODE REVIEW

**Comment by michield** [comment]
No, I don't think that's a good idea. The power of the Forward system is that the "From" is from the person you know, which makes it more likely to be opened.

I think a way to do it would be to have the "From email" be the system email, and then the "From name" be the name of the forwarder. But that may get phishing alarm bells ringing.

Also, let's not do this across the board. This is, for now, an SES problem. I think what would be good is to set up a special "forwarder email" on the system, register that with SES and then use that email address as the forward email with the "Forwarder Name" as the name, so that the recipient still gets it from the person who forwarded.

**Comment by bramley** [comment]
I suspect that the delivery of forwarded campaigns is wider than just SES. If I send a campaign to my yahoo address, then try to forward that to a gmail address it is rejected (seems to be using SPF with the From address, in addition to the SMTP FROM address which is on my domain).

image

Regarding this change, the original From address must have been verified for SES and other similar services, and must have passed any SPF and DKIM checks, so using it when forwarding seems ok.
Also, subscribers do not have names. I agree that making the name of the forwarding subscriber visible is sensible but that would need adding an extra field to the forwarding form.

Out of interest I had a look at what Mailchimp does 
image

- The From field includes my name and the From address is a mailchimp address that includes a modified version of my email address
- The Reply-to is my (the forwarding subscriber) email address
- The subject also includes my name "Duncan Cameron is forwarding an email to you"

and this is the Mailchimp forwarding form
image

**Comment by michield** [comment]
Ok, so this issue extends beyond the Forward system. Basically with DMARC, the From always needs to be from an 
authorised IP address. If say someone uses a gmail.com address as the From, the only way to get that to work well would be to use the google servers for sending. 

That means we need to create a new mailbox for sending, similar to the bounces, where the From is pointing to, which then possibly forwards to the actual address. This also means the Reply-To will be more important.

It would be nice though that the Forward system has the name of the person who forwarded it in the From. I guess we can set that up with a config that points to the "Name attributes".

All in all a little bit more work, but probably worth it. 

It's not necessary to do all that in this PR, but I do think updating it to find some way to have the forwarder as the "From Name", would be good.

**Comment by bramley** [comment]
I think that adding a mandatory "name" field to the forwarding form is simpler than trying to use an attribute if it exists.

Is this sufficient for the time being?

- From field - original From address with the entered name
- Reply to - the address of the subscriber who is forwarding with the entered name

**Comment by michield** [comment]
Yes, that makes sense. I don't see the change in the code though?

**Comment by bramley** [comment]
It needed a bit more work but is there now. On the Forward form the subscriber has to enter their name, which is used for the From and Reply-To addresses.
Also changed the presentation of the Forward form for the mandatory fields to appear similar to other front-end pages.

**Pull request merged**
