### PR TITLE
fix invalid SQL causing database initialisation errors.

### PR DESCRIPTION
**Pull request by onlyjob**
Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>

### CODE REVIEW

**Comment by michield** [comment]
can you explain why that is an improvement? To me, both formats are equivalent:

https://dev.mysql.com/doc/refman/5.0/en/replace.html

**Comment by onlyjob** [comment]
I'm not sure why but original code is not working on Debian Jessie with MySQL 5.5.42.
I also fail to see the problem with `SET` notation but it is just doesn't work -- perhaps Oeacle changed some defaults? I've tested the change successfully and I am confident that it fixes the problem.

**Comment by onlyjob** [comment]
Alternatively I may have missed minor syntax error producing invalid SQL but now it fixed...

**Comment by michield** [comment]
Before I can merge, would you mind [signing the CLA](https://www.phplist.com/cla) ?

**Comment by michield** [comment]
Odd by the way, I use "mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3" and the original code works fine. I wonder if it's something else.

**Comment by onlyjob** [comment]
> Before I can merge, would you mind signing the CLA ?

I feel uncomfortable signing any kind of CLA.
I agree with terms of AGPL-3+ and the very fact of my contribution confirms that AGPL-3+ will be governing my contribution to the project.
CLA is unnecessary and very unusual for AGPL-3 licensed project. 

AGPL demands that any _phpList_ user should share their improvements to _phpList_.
Why being compliant with license terms is not enough?
I have a feeling that by asking contributors to sign CLA you create conflict with AGPL-3 spirit and that CLA might dramatically diminish number of contributors and their willingness to help.

You may find interesting that there are rumors that _systemd_ was made merely because developers could not merge their improvements with _upstart_ due to contribution agreement. It could be that the latter actually defined the destiny of a project...

**Comment by onlyjob** [comment]
> and the original code works fine. I wonder if it's something else.

very odd indeed. By there is no mistake, original code somehow generated invalid SQL.
I even picked sample from `/tmp/queries.log` and tried to run it manually. I couldn't recognise syntax error so I've experimented with quoting for a while but managed to make it work by using `VALUES` syntax. Database was initialised with `CREATE DATABASE phplistdb DEFAULT CHARACTER SET utf8`.

**Comment by michield** [comment]
> I have a feeling that by asking contributors to sign CLA you create conflict with AGPL-3 spirit and that CLA might dramatically diminish number of contributors and their willingness to help.

Yes, I'm aware of that. But I'm prepared to take that risk. The CLA gives me the flexibility to explore different income streams, which otherwise would not be possible. Finding a good way to run healthy businesses based on Open Source is for everyone's benefit, most importantly the Open Source community. For 15 years I've been looking for this, and a contribution of a few hours tops should not impede that. The CLA guarantees the code to be AGPL, but allows me to close it for potential clients who cannot operate with FOSS as it stands, eg governments and others.

**Comment by onlyjob** [comment]
When I contribute I want guarantees that my contribution will never be closed under any circumstances. (A)GPL is guarantees that and I won't give anyone unfair advantages.

With all due respect it is not true that governments can not operate FLOSS. As a matter of fact number of governments are beginning to realise that they can not operate non-FLOSS due to all the risks and insecurity, lack of peer review/audit etc. Open source community will not benefit from exceptions. IMHO it would be best if you obey licensing terms just like everyone else.

Speaking about this particular contribution it is probably not copyright-able since it is very small, changes very little and introduces no new logic whatsoever.

**Comment by michield** [comment]
I was giving the government as example, and maybe a wrong one, but it's the principle of having the flexibility. I have no plans to do so, but I don't want to close the door on it either. If you have a compelling contribution that I would be silly not to include, I may review this position. For now, I have no incentive to change this policy.

**Comment by michield** [comment]
By the way, if you really want this in, you can mark the contribution as MIT licensed without signing the CLA.

But I'm not entirely convinced that the change is necessary.

**Comment by onlyjob** [comment]
Fair enough. Thank you for being flexible. Please consider my contribution [MIT](http://opensource.org/licenses/MIT)-licensed. Would you like me to add statement to commit message?

**Comment by michield** [comment]
Thanks. No, that'll be fine like that. I'll try to find someone to second this change.

**Comment by bramley** [comment]
The original statement has now been rewritten but the problem was due to missing a double-quote between single-quotes at the end of the line.

    set translation = "'. $trans. '');

**Comment by onlyjob** [comment]
Yeah, it is hard to see through this extraordinary ugly quoting... Thanks, @bramley.

**Comment by michield** [comment]
Ah, so no longer needed I guess.

**Pull request closed without merging**
