### PR TITLE
Added number formatting to process queue ajax log content

### PR DESCRIPTION
**Pull request by samtuke**

### CODE REVIEW

**Comment by michield** [comment]
did you test that ? Won't the %d turn it back into a plain integer?

**Comment by samtuke** [comment]
I don't think I can test before committing without running webbler locally; however I will test on the dev site tomorrow and check.

**Comment by bramley** [comment]
It needs to use %s instead of %d
```
php -r 'printf("Sending in batches of %d messages\n", number_format(12345));'
Sending in batches of 12 messages
php -r 'printf("Sending in batches of %s messages\n", number_format(12345));'
Sending in batches of 12,345 messages
```

**Comment by samtuke** [comment]
Simple mistake, sorry, will fix.

**Comment by samtuke** [comment]
I believe the issues have been fixed with the new commits; reopening PR

**Comment by michield** [comment]
Hmm, I try to avoid changes like that, because it requires all translators to re-translate those strings. Some languages are not actively translated and would therefore "regress". It's tricky. 

I'll do it this time, but we should be careful changing things too much, if it's not really essential, for the above reason.

**Pull request merged**
