### PR TITLE
Add campaign click ratio to statistics page

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=18538
The click rate shows the number of clicks on the campaign divided by the number of times the campaign is viewed, expressed as a percentage.

### CODE REVIEW

**Comment by bramley** [comment]
I don't think that this is the correct change because the existing code is incorrect, and you have based the change on that.  The current code already intends to display a number of clicks and a clicked/sent % but only the % is displayed. 
image

This is caused by a repeated error in calling addColumn() with the same first and second parameter values
`$ls->addColumn($element, '', !empty($clicked[0]) ? PageLink2('mclicks&id='.$id, $clicked[0]) : '0');`
`$ls->addColumn($element, '', $perc.' %');`

only the final call of addColumn() will be used

I suggest reworking the current code to make that display correctly then re-apply your change. One way to display several values in one column is to use a separator, for example 
58 | 19.6% | 29.6%
but this would need an explanation somewhere as what the two % figures actually mean.

**Comment by bramley** [comment]
Sorry, my previous comments were wrong. Your change is fine, but there is the existing problem with how addColumn() is used. Maybe you would like to look into fixing that?

**Comment by michield** [comment]
@bramley I'm not sure what you mean with the addColumn issue. Please send a PR if you think something needs fixing

**Comment by bramley** [comment]
I misunderstood what the code is trying to do. 
It appears to want to display an opened total and an opened % but only the latter is actually displayed. Similarly for clicks - a clicked total and a clicked/sent %.
The problem is that there are duplicate element names - Opened and Clicked are used for the total and for the %, so only the latter is displayed.

Originally I thought it was trying to display extra columns, not extra elements.

**Pull request merged**
