### PR TITLE
Added new mince configuration file for use with mince minifier

### PR DESCRIPTION
**Pull request by samtuke**
This config file should allow anyone to minify css when the mince command is executed from within the ui directory. All paths are relative. Tested locally successfully.

### CODE REVIEW

**Comment by michield** [comment]
sorry there seems to be duplication in this file

**Comment by bramley** [comment]
@samtuke What is the purpose of this new file, as there is already a .minceconf file in the admin directory?

**Comment by michield** [comment]
Yes, I agree. In fact, I'm suspicious this is the cause of the Minified CSS issue. Could that be?

**Comment by samtuke** [comment]
@bramley I wasn't aware there was already a .minceconf file. If the other one works well then mine is redundant.

**Comment by michield** [comment]
already there

**Pull request closed without merging**
