### PR TITLE
make sure the [LOGO] placeholder works, as well as eg [LOGO:50]

### LINKED ISSUE #944: [LOGO] placeholder in campaigns stopped working
When you use [LOGO] in a campaign, it is replaced with ORGANISATIONLOGO500.png

### PR DESCRIPTION
**Pull request by michield**
## Description
Fixed #944

### CODE REVIEW

**Comment by michield** [comment]
I don't think this has worked for a long time. Strange it was never found before.

**Comment by bramley** [comment]
I don't understand this. Using `` in a template works for me.

**Comment by michield** [comment]
Ah, that's a good point. I made it work without the  but I'm not sure what the docs say how to use it.

**Comment by michield** [comment]
Yes, you're right. I thought that [LOGO] would add the image, but you need to put the tags around it. I'll close this, as it will break existing templates that use &lt;img src="[LOGO]" /&gt;

It just needs better guidelines I guess.

**Pull request closed without merging**
