### PR TITLE
Fatal error in hu translation

### PR DESCRIPTION
**Pull request by szepeviktor**
No is "Nem" in Hungarian.

### CODE REVIEW

**Comment by michield** [comment]
Translations need to be edited on https://translate.phplist.org

**Comment by szepeviktor** [comment]
@michield Thank you. Currently I have no time to register and log in and get familiar with the UI.

**Comment by samtuke** [comment]
@szepeviktor Thank you for your contribution!

I have applied your translation here: https://translate.phplist.org/hu/phplist/translate/phplist.po#unit=142026 As @michield says, that's the best place to add translations.

I merged the PR in order to test updating the strings in Pootle (the software running on translate.phplist.org) directly from Git, as a Pootle Admin. This failed due to an authentication issue that I'll work on.

**Comment by michield** [comment]
@samtuke merging here may cause mayhem with the translation system. Please avoid doing that.

**Pull request merged**
