### PR TITLE
#0019164: Send test from Template only available for System Template

### PR DESCRIPTION
**Pull request by mariez**

### CODE REVIEW

**Comment by michield** [comment]
The send test on templates is not like campaigns. There is no content to send. So, the send Test in templates will send the transaction messages as the content.

That is the reason we are only sending tests on templates with the system template.

If you want that to change you'd need to think about what content to send in the test messages, or maybe empty content? Or Lorem Ipsum.

**Comment by mariez** [comment]
The commit only uncomment the if statement that use to hide the send test panel on non system templates.

**Comment by michield** [comment]
Yes, and as a result non-system templates will be able to be used to send test mails. That may not be desired functionality.

**Comment by mariez** [comment]
@michiel I think maybe I am not using the right words. I will try to explain myself again. 

Actually, the "send test" panel is shown with all templates, thats why @suelaP  reported the issue: https://mantis.phplist.org/view.php?id=19164 asking to hide the "send test" button on non-system templates, because is not usefull for that templates.

When I open template.php I see that there is an if statement at the bottom to hide the "send test" panel on non-system templates. Thats great, but that if statement, actually is commented, so is not doing what it supose to do. Thats why actually we have the issue that the "send test" panel is shown on non-system templates. 

So, with this commit, I am triying to remove the comments and let the if statement work againg and hide the "send test" panel.

**Comment by michield** [comment]
Yes, I know what will happen when we do this. I'm just trying to flag up that I'm not sure that we want that to happen. I think it will be very confusing UX. On the template page (without actual campaign content to send for testing) only sending the system template as a test makes sense. Not any other template.

**Comment by michield** [comment]
Ok, my bad. I completely read is the opposite of how it is. Instead of removing the condition, you are re-adding it. Sorry to cause all the confusion. I just don't understand how it got to be as it as in the first place.

**Comment by michield** [comment]
Wow, it's been like that for 4 years, amazing: https://github.com/phpList/phplist3/commit/a3bf8d3fcfc85a7b4b816f1666be7781c4e80dbf

**Comment by michield** [comment]
And not only that, I made that change. Ouch. 
https://mantis.phplist.org/view.php?id=17462

**Pull request merged**
