### PR TITLE
Add organisation name placeholder

### PR DESCRIPTION
**Pull request by xh3n1**
## Description
Make the organisation name accessible via [ORGANISATION_NAME] placeholder.

## Related Issue

https://mantis.phplist.org/view.php?id=19804

### CODE REVIEW

**Comment by bramley** [comment]
I think this needs to use a global variable $organisation_name instead of the config table value. See this code in connect.php that sets the website, domain and organisation name when the config table values are empty.
```
$organisation_name = getConfig('organisation_name');
$domain = getConfig('domain');
$website = getConfig('website');
if (empty($domain)) {
    $domain = $_SERVER['SERVER_NAME'];
}
if (empty($website)) {
    $website = $_SERVER['SERVER_NAME'];
}
if (empty($organisation_name)) {
    $organisation_name = $_SERVER['SERVER_NAME'];
}
```

**Comment by suelaP** [comment]
I think that it would be better to leave it blank that replace it with the installation name. 
If I have the name of my installation "xyznews" I wouldn't like that my "xyz" company is shown with that name. 

I think the best approach is to replace the placeholder with a default value on template preview that shows the user that it needs to be provided. 

Something like [EDIT: ORGANIZATION NAME EXAMPLE]

**Comment by xh3n1** [comment]
@suelaP I pushed the changes for "preview template" as suggested.

**Comment by bramley** [comment]
@xh3n1 
This line doesn't look seem to do anything
`$template = str_ireplace('[ORGANISATION_NAME]', '[ORGANISATION_NAME]', $template);`

@suelaP Also, as I mentioned before there is already a fallback for the organisation name when it is empty. 
The organisation name is already used as a placeholder in the front-end public pages. So if you want to change the fallback to something else then it needs to be consistent.

**Comment by xh3n1** [comment]
@bramley that line is for preview template only. When organisation name is NOT set it will display [ORGANISATION_NAME] as fallback text when you view template, as a way to tell the users about that placeholder.

**Pull request merged**
