### PR TITLE
Not send unsubscribe confirmation emails When a user opts out

### PR DESCRIPTION
**Pull request by jd440**
In order to get Best pratice It would be better to not send confirmation emails when customer Opt out.

### CODE REVIEW

**Comment by samtuke** [comment]
@jd440 Thanks for the PR! An additional review by @michield is required to merge.

**Comment by samtuke** [comment]
Note: if this is merged then documentation about the new config variable will be required here: https://resources.phplist.com/system/config/variables

**Comment by jd440** [comment]
@samtuke it's long time I use phplist so if I could help…
About documentation have I something to do?

**Comment by samtuke** [comment]
@jd440 Not just yet; let's wait for @michield's review first. The docs at the link above can be very short in any case. Thanks!

**Comment by michield** [comment]
Instead of   

`             if (!defined('UNSUBSCRIBE_NOCONFIRMATION') || (UNSUBSCRIBE_NOCONFIRMATION == 0)) {`

The common way in phpList is to define it in init.php and then use

`               if (! UNSUBSCRIBE_NOCONFIRMATION) {`

**Comment by jd440** [comment]
thanks @michield 
I hesitate to add in init.php

```
if (!defined('UNSUBSCRIBE_NOCONFIRMATION')) {
    define('UNSUBSCRIBE_NOCONFIRMATION', 0);
}
```

Do you want me to made an new commit?

**Comment by samtuke** [comment]
Thanks @jd440; please can you clarify your intention behind the additional commits made today?

**Comment by michield** [comment]
@jd440  it would be good to split your PRs by functionality

**Comment by bramley** [comment]
Something else needs to be included in this change, the text displayed on the unsubscribe page when the person confirms the unsubscription. The text states that a confirmation message will be sent.

image

**Comment by michield** [comment]
Yes, good point. And @jd440  please remove the pop before smtp stuff, as that's something completely different. You can create a new branch to PR that separately.

**Comment by jd440** [comment]
Hi everyone,

Sorry about the commit I did yesterday, As you could guess it wasn't intentional, I'm newbie on git
I wanted to push 2 different commit on 2 pull request, but both have been mixed.

Yesterday, I just understand, the branch stuff.
But as my first commits have been made on my master, now both are mixed
I don't know  how could remove the "pop before smtp stuff" commit, and how could i create a new branch without this first commit.

Anyway, as soon as I fix my branch problem, I push correction about confirmation message notice by @bramley

**Comment by bramley** [comment]
> I don't know how could remove the "pop before smtp stuff" commit, and how could i create a new branch without this first commit.

A simple way is to make two branches from master, then undo all the commits in master so that it is back at its original state. You can then edit each of the branches to remove the stuff that should not be there.

**Comment by jd440** [comment]
@bramley is there any way to send you PM, to ask you to help me?
To not polluate pull request?

**Comment by samtuke** [comment]
@jd440 You may also want to check the `git cherry-pick` command, which lets you copy specific commits (including ranges) from one branch to another.

**Comment by bramley** [comment]
> is there any way to send you PM, to ask you to help me?

You can open a new topic in the forum, no need for it to be private.

**Pull request closed without merging**
