### PR TITLE
Fixes for php8

### PR DESCRIPTION
**Pull request by michield**
## Description
Some more tweaks for PHP8

### CODE REVIEW

**Comment by bramley** [comment]
Regarding the PHP IMAP bug you can simply move the CL_EXPUNGE flag to the imap_close() function, that is not affected by the imap_open() problem. Or explicitly call imap_expunge() just before imap_close().

**Comment by michield** [comment]
Ah, good point, let me do that.

**Comment by michield** [comment]
So, basically that negates the need to work around that bug, and simply run it on close, instead of open.

https://github.com/phpList/phplist3/pull/745/commits/964acdab12c57299980a001e1260d60f5266e238

I think that will do it, but let me know if you spot anything.

**Comment by bramley** [comment]
There is another use of CL_EXPUNGE in the function processMbox() that needs to be changed.

**Comment by bramley** [comment]
> There is another use of CL_EXPUNGE in the function processMbox() that needs to be changed.

I think that you may have missed this comment.

**Comment by michield** [comment]
I had seen that, and will pick it up when I do another PHP8 bug search session.

**Pull request merged**
