### PR TITLE
StyleCI / PHP-CS-Fixer

### LINKED ISSUE #29: Coding Style conventions
Do you follow some Coding Style conventions?

I would recommend to follow at least PSR-1/2 and maybe [Symfony](http://symfony.com/doc/current/contributing/code/standards.html) conventions.

I can propose some automatic tools to help with it.

Tell me if you are interested. :+1:

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #29.

I added Symfony preset by default + some fixers.

Feel free to tell me if you want to change that.

I also fix CS on a separated commit. If you want to do it yourself, I can revert it.

For StyleCI, just login with github at https://styleci.io/ and enable your repository.

I'll work on phplist 4 once this PR will be merged.

Regards.

### CODE REVIEW

**Comment by michield** [comment]
Hmm, I can't really accept a PR this big. That will make it impossible to retrace activity.

Can you just do a PR with the files for the settings and then how to run it on the code? Then we can gradually apply it over time.

**Comment by Soullivaneuh** [comment]
@michield Done. 

Just run `php-cs-fixer fix -v .` to get files corrected. More info: http://cs.sensiolabs.org/

Don't forget to activate StyleCI before merge this PR. :-)

Oh, and I also optimized your composer.json file BTW. Testing deps should be on `require-dev` section, not `require`.

**Comment by michield** [comment]
That's great thanks. I have looked into the cs-fixer myself before, but it's great to have it all configured and ready to go.
Just to make it easier to merge the PR, could you sign the [CLA](https://www.phplist.com/cla) ? 

Thanks

**Comment by Soullivaneuh** [comment]
> Awesome, you have signed the phpList CLA
Your github login: Soullivaneuh
Your name: Sullivan SENECHAL
Date signed: 2015-10-07

But would not be simpler to put a LICENSE file one the repository? This is the first time I'm asked to do this kind of think.

**Comment by michield** [comment]
Great, thanks. Yes, the license is here: [COPYING](https://github.com/phpList/phplist3/blob/master/COPYING) The CLA is to allow more centralised protection of that.

**Comment by michield** [comment]
Hmm, this StyleCI site is failing. Did I merge too early?

Broken File - public_html/lists/admin/send_core.php

PHP Parse error: syntax error, unexpected '$messagedata' (T_VARIABLE) in tmpotA1JN on line 197.

**Comment by Soullivaneuh** [comment]
> Hmm, this StyleCI site is failing. Did I merge too early?

Did you run cs-fixer and pushed after that?

Can I have the StyleCI like please?

**Comment by michield** [comment]
no didn't run it. Will try on a branch.

What's the  "StyleCI like" ?

**Comment by Soullivaneuh** [comment]
Sorry, I wanted to say "link". :-)

**Comment by Soullivaneuh** [comment]
> no didn't run it. Will try on a branch.

That's why StyleCI does not like your coding style. :-)

**Comment by michield** [comment]
You mean [this link?](https://styleci.io/repos/32042787)

How do I exclude paths in the cs-fixer? It doesn't make sense to include PHPMailer and other 3rd party stuff.

**Comment by Soullivaneuh** [comment]
For the parse error, it seems your php file is broken.

> How do I exclude paths in the cs-fixer?

On your `.styleci.yml`:

```yaml
finder:
  exclude:
    - "somedir"
```

See https://styleci.readme.io/docs/configuration

**Comment by michield** [comment]
>  it seems your php file is broken

https://dev.phplist.com/lists/admin/ always runs the latest code, all is fine. It looks like the StyleCI checkout of the code has failed.

Thanks for the pointer to the config

**Comment by Soullivaneuh** [comment]
> > it seems your php file is broken

> https://dev.phplist.com/lists/admin/ always runs the latest code, all is fine. It looks like the StyleCI > > > checkout of the code has failed.

@GrahamCampbell what do you think about this?

**Comment by Soullivaneuh** [comment]
@michield Have you tried to run cs-fixer and push modifications on your branch to see StyleCI reaction?

**Comment by GrahamCampbell** [comment]
No need to run php-cs-fixer.

**Comment by GrahamCampbell** [comment]
StyleCI can send you a PR with the fixes. Just click the create fix PR button.

**Comment by GrahamCampbell** [comment]
You seem to have disabled StyleCI on the master branch? You'll need to enable it if you want it to fix your code for you.

**Comment by michield** [comment]
Well, I'd rather not, just verbatim like that.

**Comment by GrahamCampbell** [comment]
Not sure what you mean? No point in having StyleCI if you don't want to use it?

**Comment by michield** [comment]
I'm evaluating, and the parse error doesn't contribute to my confidence

**Comment by GrahamCampbell** [comment]
What parse error?

**Comment by GrahamCampbell** [comment]
That error normally happens when StyleCI checks your own code and finds you already have a syntax error in there before it trys to change anything.

**Comment by michield** [comment]
there is no syntax error there, that's my point

**Comment by GrahamCampbell** [comment]
Well there is no parse error then?

**Comment by GrahamCampbell** [comment]
Can I see please?

**Comment by GrahamCampbell** [comment]
Do you have an analysis ID so I can look it up on our logs?

**Comment by michield** [comment]
read back in this thread, it's all there.

**Comment by GrahamCampbell** [comment]
I've just kicked off a new analysis on our system so I can see what happens for myself.

**Comment by GrahamCampbell** [comment]
I guess the issue here is you're trying to analyse external libraries too, and they need excluding.

**Comment by GrahamCampbell** [comment]
https://styleci.io/analyses/qvRmxq

**Comment by GrahamCampbell** [comment]
Is that the issue?

**Comment by GrahamCampbell** [comment]
That normally happens when there is a missmatch of curly braces in the phpdoc.

**Comment by GrahamCampbell** [comment]
https://github.com/phpList/phplist3/pull/32 might just fix this.

**Comment by michield** [comment]
Yes, excluding the external libraries, agreed, and working on that

**Comment by GrahamCampbell** [comment]
Note that StyleCI didn't break your code. It stopped the analysis and notified you of the issue. :)

**Comment by michield** [comment]
Cool, thanks. Bit late here, will check tomorrow. So, you're saying, StyleCI broke on a hashed comment and a space?

**Comment by GrahamCampbell** [comment]
No, it seems it didn't. I'm trying to debug it now, since that change I made in the PR didn't fix it.

**Comment by GrahamCampbell** [comment]
In the meanwhile, I've disabled your branches on StyleCI again.

**Comment by GrahamCampbell** [comment]
Running some tests on my fork now.

**Comment by michield** [comment]
Ok. My code is 15 years old :-) If you can handle this, you can handle a lot :-) It was originally coded for PHP 3.

I'm signing off now, but will check tomorrow. Cheers!

**Comment by GrahamCampbell** [comment]
Sure. :)

**Comment by GrahamCampbell** [comment]
I'm going to have to go to bed now, but I'll try to see what's going on tomorrow. Also, I think it might be safe to fix the indentation using an ide first, then using StyleCI to fix the rest, because StyleCI can still make some bad inferences regarding indentation. That stuff is pretty hard to do. :)

**Comment by Soullivaneuh** [comment]
> No need to run php-cs-fixer.

I agree, it's not necessary.

It's a choice for maintainer and contributors. Web interface or command line, it's up to you! ;-)

**Comment by michield** [comment]
Well, sure, if the web interface works of course. Otherwise there's no choice.

**Comment by michield** [comment]
I manually ran php-cs-fixer on that file send_core.php and it's making a mess of it. Indentation is worse than it was before running it.

this is why doing things like this across the board is a bad idea. It's likely to be great for most of the code, but still needs checking to be sure.

**Comment by GrahamCampbell** [comment]
> Indentation is worse than it was before running it.

As I said, you need to fix the indentation first with an IDE before getting started with anything else.

**Comment by michield** [comment]
[StyleCI](https://styleci.io/repos/32042787)

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
