### PR TITLE
Improve the appearance of user check page

### PR DESCRIPTION
**Pull request by xh3n1**
-Removed the duplicated emails
-Display key column only if its not null
-Removed the "duplicated" continue button

Before:
screen shot 2018-07-12 at 16 59 57
After : 
screen shot 2018-07-12 at 17 36 38

### CODE REVIEW

**Comment by xh3n1** [comment]
Mantis issue: https://mantis.phplist.org/view.php?id=19320

**Comment by bramley** [comment]
This page has different labels for foreign key 'Foreign Key' and 'key'. Perhaps use just 'Foreign Key' in both.

setElementHeading() applies to the WebblerListing so need be called only once outside of the loop, not for each email/foreign key

The non-existing subscribers listing displays either an email address or a foreign key (depending on which radio button was selected) so the heading should reflect that.
image

What is the reason for changing htmlspecialchars() to htmlentities()?

**Comment by bramley** [comment]
Using strip_tags() looks odd, because it means the value displayed in the listing can be different to that which was entered and used to match an email address or foreign key.

image

I think that using htmlspecialchars() on the entered value should be sufficient.

**Comment by xh3n1** [comment]
@bramley Thank you for the review. 
1. There are two different WebblerListing ($lsexist and $lsnonexist) and it needs to be applied to both.
2. Regarding the headings, I think that one should see the corresponding email address of the foreign key entered and vice versa if it exists and either email address or a foreign key (depending on which radio button was selected) if it doesn't exist.
3. Use htmlentities() instead of htmlspecialchars() because htmlspecialchars() translates only some set of characters (http://php.net/manual/en/function.htmlspecialchars.php). For full entity translation, htmlentities is recommended. Anyway on "textarea" context, using htmlspecialchars is also fine.
4.  I agree with you about strip_tags, I applied htmlentities and stripslashes to that element as well.
5. Regarding the "continue" button I agree with you about decreasing the height of the textarea, but I think that the button should be positioned at the bottom.

**Pull request merged**
