### PR TITLE
Escape list description content on index page

### PR DESCRIPTION
**Pull request by xh3n1**
I have used htmlentities to escape list description content to prevent malicious tags on index page (/lists/?p=subscribe&id=).

### CODE REVIEW

**Comment by michield** [comment]
I think we should allow admins to have HTML in the description of a list. This will stop that and render the page very strangely. Maybe we should only allow some tags and strip <script> and other ones, but I do think we want to allow HTML.

**Comment by samtuke** [comment]
List description is somewhat confusing currently as it is used on both public and private pages. I would expect HTML content on the public pages, but not on the private pages, and the nature of the description is potentially different. Thoughts @suelaP ?

**Comment by samtuke** [comment]
@suelaP Ping

**Comment by suelaP** [comment]
@samtuke  > @xh3n1 will review this again following a conversation we all had about this.

**Comment by samtuke** [comment]
Ping

**Comment by samtuke** [comment]
Ping

**Comment by samtuke** [comment]
Ping

**Comment by samtuke** [comment]
Ping

**Comment by michield** [comment]
This needs rethinking, and can't merge as is

**Pull request closed without merging**
