### PR TITLE
Identifying the subscriber for a bounce

### PR DESCRIPTION
**Pull request by bramley**
## Description

In bounce processing when identifying the subscriber use the fallback only when the X-ListMember header is not present.

Currently, if the X-ListMember header is present but with a non-existent subscriber then the fall-back processing takes place and can misleadingly find another email address.
In my case, it found the From header address and associated the bounce with that subscriber. It seems to be better to just treat the bounce as an unidentified subscriber instead.

### CODE REVIEW

**Comment by michield** [comment]
I think it may be more reliable to use the List-Unsubscribe header

`List-Unsubscribe: <http://[domain]/lists/?p=unsubscribe&uid=[uniqid]&jo=1>`

when you get the uniqid, it'll be quite certain who to look for.

What do you think?

**Comment by bramley** [comment]
So long as the original headers are included in a bounce then uniqid or email would work. In either case the code needs to handle the subscriber not existing, say due to having been deleted by earlier bounce processing.

I think getting the subscriber using only one header (X-ListMember or List-Unsubscribe) is clearer than trying to use the fallback processing (which I think anyway is a bit dangerous as it is unpredictable).

**Comment by michield** [comment]
Ah, yes, I see your point. We should use known headers only, let's just zap this fallback, as it's unpredictable.

**Comment by bramley** [comment]
Trying to use List-Unsubscribe  might be difficult. I have noticed that phpmailer now encodes "long" header lines when sending using the php mail() function. This is how that header appears in a bounce email

```
List-Unsubscribe: =?us-ascii?Q?<https://www.mysite.org/lists/=3Fp?=
 =?us-ascii?Q?=3Dunsubscribe&uid=3D1234567893f98df76aaf84923b?=
 =?us-ascii?Q?7de3f6&jo=3D1>?=
```

**Comment by michield** [comment]
Yes, I think the logic is good. Let's go with it. It makes sense to avoid looking for any email, as that can have strange consequences. 

Marking as ready to merge.

**Comment by bramley** [comment]
This change still has the fallback. It sounds like you would like that removed.

**Comment by michield** [comment]
Well, it only fires when the X-ListMember is not there, so it'll fine to leave it

**Pull request merged**
