### PR TITLE
Use translation in subscribe button (Subscribe page)

### PR DESCRIPTION
**Pull request by asosso**

### CODE REVIEW

**Comment by samtuke** [comment]
@asosso Thanks for the PR! It looks like this is the first time you've patched phpList 3 core - if so, please could you take a few seconds to agree to the CLA?: https://phplist.com/cla

**Comment by asosso** [comment]
@samtuke I signed the cla!

**Comment by samtuke** [comment]
@asosso Thanks! Just need a review and then we're good to go.

**Comment by asosso** [comment]
@xh3n1 thank you! I missed that field.
I couldn't understand why it wasn't translated

**Pull request closed without merging**
