### PR TITLE
Update Version to last 3.6.8 Tag

### PR DESCRIPTION
**Pull request by sbaghdadi**

### CODE REVIEW

**Comment by sbaghdadi** [comment]
Because of missing updated version in file, in phplist backend, upgrade wizard won't start and backend gives a message a new version (3.6.8) is out.

**Comment by SetteT3** [comment]
I need this change too. Please merge as soon as possible. Thank you

**Comment by michield** [comment]
Interesting. That file is not used at all in the application, only if you run it from git. Are you saying you run phpList from git and update that way? If that's the case, we may have to redesign the release process a little.

**Comment by michield** [comment]
The VERSION in the download file is changed here: https://github.com/phpList/phplist3/blob/master/.github/workflows/build-release.yml#L141

so the zip file always has the correct version on that file, but that is not committed to the repository

**Comment by sbaghdadi** [comment]
We don't use the git version directly, but through composer (which also just pulls the git files). We have made our own composer.json, and we are building and delivering phplist through gitlab-ci fully automated.

Here is our composer.json (feel free to use it if somebody want to!)
`{
    "name":"cpsit/newsletter",
    "description":"A Newslettersystem based on phplist",
    "authors":[
        {
            "name":"xxx",
            "email":"xxx"
        }
    ],
    "repositories":[
        {
            "type":"package",
            "package":[
              {
                "type":"cpsit-phplist",
                "name":"cpsit/phplist",
                "version":"3.6.6",
                "require":{
                  "php":"^5.3.3 || ^7.0"
                },
                "config":{
                  "bin-dir":"vendor/bin/"
                },
                "source":{
                  "url":"https://github.com/phpList/phplist3.git",
                  "type":"git",
                  "reference":"v3.6.6"
                },
                "extra":{
                  "installer-name":"cpsit-phplist"
                }
              },
              {
                   "type":"cpsit-phplist-plugin-ckeditor",
                   "name":"cpsit/phplist-plugin-ckeditor",
                   "version":"2.1.5",
                   "source":{
                       "url":"https://github.com/bramley/phplist-plugin-ckeditor.git",
                       "type":"git",
                      "reference":"2.1.5"
                   },
                   "extra":{
                       "installer-name":"cpsit-phplist-plugin-ckeditor"
                   }
              },
              {
                   "type":"cpsit-phplist-plugin-common-plugin",
                   "name":"cpsit/phplist-plugin-common-plugin",
                   "version":"3.9.8",
                   "source":{
                       "url":"https://github.com/bramley/phplist-plugin-common.git",
                       "type":"git",
                       "reference":"3.9.8"
                   },
                   "extra":{
                       "installer-name":"cpsit-phplist-plugin-common-plugin"
                   }
              },
              {
                   "type":"cpsit-phplist-plugin-restapi",
                   "name":"cpsit/phplist-plugin-restapi",
                   "version":"1.0.0",
                   "source":{
                       "url":"https://github.com/phpList/phplist-plugin-restapi.git",
                       "type":"git",
                       "reference":"master"
                   },
                   "extra":{
                       "installer-name":"cpsit-phplist-plugin-restapi"
                   }
              },
              {
                   "type":"cpsit-phplist-plugin-segment",
                   "name":"cpsit/phplist-plugin-segment",
                   "version":"2.7.0",
                   "source":{
                       "url":"https://github.com/bramley/phplist-plugin-segment.git",
                       "type":"git",
                       "reference":"2.7.0"
                   },
                   "extra":{
                       "installer-name":"cpsit-phplist-plugin-segment"
                   }
              },
              {
                   "type":"cpsit-phplist-plugin-invite",
                   "name":"cpsit/phplist-plugin-invite",
                   "version":"0.4.0",
                   "source":{
                       "url":"https://github.com/phpList/phplist-plugin-invite.git",
                       "type":"git",
                       "reference":"master"
                   },
                   "extra":{
                       "installer-name":"cpsit-phplist-plugin-invite"
                   }
              }
            ]
        }
    ],
    "require":{
      "composer/installers":"~1.0",
      "oomphinc/composer-installers-extender":"^1.1.2",
      "cpsit/phplist":"3.6.6",
      "cweagans/composer-patches": "^1.6",
      "cpsit/phplist-plugin-ckeditor": "2.1.5",
      "cpsit/phplist-plugin-common-plugin": "3.9.8",
      "cpsit/phplist-plugin-restapi": "1.0.0",
      "cpsit/phplist-plugin-segment": "2.7.0",
      "cpsit/phplist-plugin-invite": "0.4.0"
    },
    "config":{
        "vendor-dir":"app/vendor",
        "web-dir":"app/web"
    },
    "extra":{
        "installer-types":[
            "cpsit-phplist",
            "cpsit-phplist-plugin"
        ],
        "installer-paths":{
            "app/web":[
                "type:cpsit-phplist"
            ],
            "app/web/public_html/plugins":[
                "type:cpsit-phplist-plugin-ckeditor",
                "type:cpsit-phplist-plugin-segment",
                "type:cpsit-phplist-plugin-restapi",
                "type:cpsit-phplist-plugin-common-plugin",
                "cpsit-phplist-plugin-invite"
            ]
        },
      "patches": {
        "cpsit/phplist": {
          "config Patch": "patches/config.patch",
          "defaultFrontendTexts Patch": "patches/defaultFrontendTexts.patch",
          "Index Patch": "patches/index.patch",
          "Lib Patch": "patches/lib.patch",
          "sendMailLib Patch": "patches/sendemaillib.patch"
        }
      }
    },
  "scripts": {
    "move-folders": [
      "#copy plugins! If you see errors that means your using windows. Please copy files by hand.",
      "cp -R app/vendor/cpsit/phplist-plugin-common-plugin/plugins/* app/web/public_html/lists/admin/plugins",
      "cp -R app/vendor/cpsit/phplist-plugin-segment/plugins/* app/web/public_html/lists/admin/plugins",
      "cp -R app/vendor/cpsit/phplist-plugin-restapi/plugins/* app/web/public_html/lists/admin/plugins",
      "cp -R app/vendor/cpsit/phplist-plugin-ckeditor/plugins/* app/web/public_html/lists/admin/plugins",
      "cp -R app/vendor/cpsit/phplist-plugin-invite/plugins/* app/web/public_html/lists/admin/plugins",
      "#copy plugins finished!"
    ],
    "copy-assets": [
      "",
      "#copy Assets",
      "cp -R asset/images app/web/public_html/",
      "cp -R asset/lang/texts app/web/public_html/lists/",
      "cp -R asset/ui/phplist-ui-bootlist app/web/public_html/lists/admin/ui/",
      "cp -R asset/frontend app/web/public_html/lists/",
      "#copy Assets END"
    ],
    "create-symlinks": [
      "",
      "#create symlinks",
      "ln -sf ../js app/web/public_html/lists/admin/ui/js",
      "ln -sf admin/ui app/web/public_html/lists/ui",
      "#create symlinks END"
    ],
    "post-autoload-dump": [
      "@move-folders",
      "@copy-assets",
      "@create-symlinks"
    ]
  }
}
`

For this case, it is necessary that the version file in github matches the version of the tag. It’s a modern and common way to handle php based the systems, so it would be really great if you just could bump the version in the file of repository and not just only the release-zip-file.

**Comment by michield** [comment]
It may be better to recode this part: https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/init.php#L11

that is also changed on release. Yes, the phpList release is also created with composer, see https://github.com/phpList/phplist3/blob/master/composer.json and https://github.com/phpList/phplist3/runs/6623182930?check_suite_focus=true#step:9:42

I'll have a think about this. It's not common practice to let a pipeline alter the code, so that would require a human action, which I was trying to avoid.

**Comment by michield** [comment]
It doesn't make sense to do this with a simple PR like this. Instead, we need to review the way that versions are managed. If you want to raise an issue instead. we can discuss it there. If we were to merge this, you'd always be one version behind.

**Pull request closed without merging**
