### PR TITLE
When using domain throttling, apply delay only when email was sent

### PR DESCRIPTION
**Pull request by bramley**
## Description

When using domain throttling, if sending to an email address is rejected because the limit on its domain has been reached  and an email was not sent, the delay of `MAILQUEUE_THROTTLE` is still applied. This seems unnecessary and slows down the sending rate.

The first commit is to apply `MAILQUEUE_THROTTLE` and `MAILQUEUE_AUTOTHROTTLE` only when the domain was not throttled. 
I don't fully understand the `$running_throttle_delay` processing so have left that as it is.

The second commit is to simplify the initialisation of the `$domainthrottle` array into one place, when a new domain is met or a new interval is started for an existing domain.

### CODE REVIEW

**Comment by michield** [comment]
When DOMAIN_AUTO_THROTTLE is enabled, running_throttle_delay is adjusted when needed. The main objective is to spread the sending of DOMAIN_BATCH_SIZE over the total period of DOMAIN_BATCH_PERIOD, instead of sending DOMAIN_BATCH_SIZE in the first few seconds.

**Comment by michield** [comment]
The PR diff is a bit hard to read and see the consequences of.

Can we not just add "&& $succces" to 

https://github.com/phpList/phplist3/blob/32094348a355b768ec01ed3b22ef09b3ccd5e9f1/public_html/lists/admin/actions/processqueue.php#L1220C52-L1220C52

and 

https://github.com/phpList/phplist3/blob/32094348a355b768ec01ed3b22ef09b3ccd5e9f1/public_html/lists/admin/actions/processqueue.php#L1222

**Comment by bramley** [comment]
That would probably have the same effect. Maybe then move this whole chunk 

```
                    if (isset($running_throttle_delay)) {
                        sleep($running_throttle_delay);
                        if ($counters['sent'] % 5 == 0) {
                            // retry running faster after some more messages, to see if that helps
                            unset($running_throttle_delay);
                        }
                    } elseif (MAILQUEUE_THROTTLE) {
                        usleep(MAILQUEUE_THROTTLE * 1000000);

...
                            }
                            usleep($delay * 1000000);
                        }
                    }
```
to be within this near line 1173, if it should be run only when the sending was successful and not when throttled or sending was unsuccessful.

` if ($success) {`

**Comment by michield** [comment]
Yes, that makes more sense. Do you want to update the PR to do that?

**Comment by bramley** [comment]
Yes, I will revise the pull request.

**Comment by bramley** [comment]
Now added another commit that moves the delay processing.

**Comment by michield** [comment]
It's a bit hard to test this, but I think it looks fine, so approving.

**Review by michield — APPROVED** [review]

**Pull request merged**
