### PR TITLE
added jQuery-3.3.1.min.js for lists directory and jquery-ui-1.12.1.mi…

### PR DESCRIPTION
**Pull request by BrunildaDosti**
Added jquery-3.3.1.min.js file in lists\js directory.

Added jquery-ui-1.12.1.min.css file in lists\admin\css directory.

### CODE REVIEW

**Comment by samtuke** [comment]
@BrunildaDosti Please can you remove the unused template items from your opening comment?

**Comment by samtuke** [comment]
@BrunildaDosti this appears to add rather than replace / update a copy of jQuery?

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti this appears to add rather than replace / update a copy of jQuery?

Actually, the /lists directory had an old version of jQuery, so I have replaced it with the new one.
Also, replaced jQuery UI script with a new version of jQuery-ui for Dressprow theme.

**Comment by samtuke** [comment]
> > @BrunildaDosti this appears to add rather than replace / update a copy of jQuery?
> 
> Actually, the /lists directory had an old version of jQuery, so I have replaced it with the new one.
> Also, replaced jQuery UI script with a new version of jQuery-ui for Dressprow theme.

But the following file still exist in this branch: `jquery-1.5.2.min.js` -- shouldn't that version of jQuery be removed if you've replaced it with the new one?

**Comment by BrunildaDosti** [comment]
> > > @BrunildaDosti this appears to add rather than replace / update a copy of jQuery?
> > 
> > 
> > Actually, the /lists directory had an old version of jQuery, so I have replaced it with the new one.
> > Also, replaced jQuery UI script with a new version of jQuery-ui for Dressprow theme.
> 
> But the following file still exist in this branch: `jquery-1.5.2.min.js` -- shouldn't that version of jQuery be removed if you've replaced it with the new one?

It is supposed to not be there as should be replaced with the new jQuery version . My mistake, sorry! I'm checking it again.

**Pull request closed without merging**
