### PR TITLE
Inserted help buttons into CSV import page

### PR DESCRIPTION
**Pull request by samtuke**
Refreshed version of pr #226 by @suelaP with unrelated commits removed.

### CODE REVIEW

**Comment by samtuke** [comment]
@suelaP Did we agree that @mariez would move the help buttons into the same table rows as the fields they relate to? Or do we have another solution for the layout?

**Comment by suelaP** [comment]
@samtuke , we agreed that @mariez would look for the best solution because putting them on the same row would cause problems when the content was expanded.

**Comment by bramley** [comment]
The actual alert text e.g. "The file you upload will need to have the attributes ...." is no longer translatable. Is that deliberate?

**Comment by suelaP** [comment]
No, it wasn't intentional, thank you for pointing that out.

**Pull request closed without merging**
