### PR TITLE
Pr 224

### PR DESCRIPTION
**Pull request by mariez**
@samtuke  is this what you need?

### CODE REVIEW

**Comment by samtuke** [comment]
Of all the newly listed commits, only 2a4fc97 should be left in the diff once the behat-cleanup branch is merged. This merge is blocked by behat-cleanup.

**Comment by samtuke** [comment]
@mariez Yes, thanks!

**Comment by mariez** [comment]
The problem is only with this commit: https://github.com/phpList/phplist3/pull/228/commits/69dd153223bc9f7a7ef9d3c6aae46d260d246482

If resolve this will take too long, i prefer to split this PR so I can go forward the other commits.

**Comment by samtuke** [comment]
This PR should not be blocking other commits or other PRs -- this PR must wait until the behat-cleanup branch is merged (which will likely take some weeks).

**Comment by mariez** [comment]
It is not blocking other commits, only the commits included in ths PR.

**Comment by michield** [comment]
Let's leave this for now. This PR is too big to be safe to merge

**Pull request closed without merging**
