### PR TITLE
Move "Campaigns", "Bounces", "Subscription" tabs from userhistory page to subscriber profile

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=19015
"User History" button and userhistory page also removed as described in the issue.

### CODE REVIEW

**Comment by xh3n1** [comment]
This test is failing https://travis-ci.org/phpList/phplist3/jobs/362662130#L631-L633.

**Comment by michield** [comment]
You copied the content from user_history into the user page. That will work, but the problem is that it will make the loading of that page much slower, particularly with busy systems and active users.

Instead, the content should be loaded on request when you change the tab to for example bounces. When you change tab, it should fetch the contents on the fly with an Ajax request.

That may be a little bit more complicated to achieve, so if you need help with that, let me know and we can arrange for a session to discuss it.

**Comment by michield** [comment]
I'm not sure this was ready to be merged. It still needs quite a bit of work.

**Comment by xh3n1** [comment]
@michield this hasn't been merged to master. It's a closed PR.

**Comment by xh3n1** [comment]
I did  "reset --hard" for the commits to this branch and the GitHub automatically closed it because there were no commits. I will create another one :)

**Comment by michield** [comment]
Ah, ok. Good. How odd, it looked like it had been merged. Thanks

**Pull request closed without merging**
