### PR TITLE
Introduce new notification for updates

### PR DESCRIPTION
**Pull request by xh3n1**
## Description
Done

- [x] Introduce new notification for update, 
- [x] Remove "try automatic updater beta"
- [x] Check for update every 3 days
- [x] Save check time on the first install
- [x] Do not show notification on Dev 
- [x] Hide "update now" for disabled automatic updater. 
- [x] Fix tests

## Related Issue
https://mantis.phplist.org/view.php?id=19760

TODO 

- [x] Decide if the notification should be displayed for RCs too.
- [x] Remove old notification and checks.

### CODE REVIEW

**Comment by xh3n1** [comment]
@samtuke cc: @suelaP  Please let me know if the notification should be displayed for RCs too.

**Comment by samtuke** [comment]
@xheni Thanks. @suela: over to you.

**Comment by suelaP** [comment]
I think this should be displayed for RCs too as whoever wants to test might want to see that. Other people might just ignore it. Although, I am not sure how good that will work with the check for updates every 3 days. @samtuke

**Comment by samtuke** [comment]
@suelaP For hosting services and consultants who provide phpList as a service, encouraging their users to upgrade to an unstable RC would be undesirable. As a compromise I propose having two config file settings:
- disable auto updater (disables all notifications)
- disable rc updates (shows only stable updates)

Both would be enabled by default. A possible risk is that most admins who want to prevent RC notifications would take the more extreme approach of disabling the updater completely, which would undermine the benefit of having two options.

Thoughts?

**Comment by suelaP** [comment]
I think providing options on both is the best approach, however I find the "disabled by default" for both quite radical. 

I think we can leave it disabled for RC notifications and enabled for regular updates.

**Comment by samtuke** [comment]
@suelaP Sorry, the double negatives introduced confusion -- I meant that both the config options could be set such that notifications for both RCs and stable updates would be shown by default in the interface; that was the suggestion.

**Comment by samtuke** [comment]
Rerunning Travis tests to try and get to green

**Pull request merged**
