### PR TITLE
[TASK] Require PHP >= 5.4

### LINKED ISSUE #137: Drop support for PHP 5.3
This is a "small version" of #136.

### PR DESCRIPTION
**Pull request by oliverklee**
And drop code that is required for lower PHP versions only, including
code for magic quotes or safe mode.

Fixes #137

### CODE REVIEW

**Comment by michield** [comment]
Nice one. phpList started with version 3 :-) Files were even called  .php3 in the beginning.

**Comment by bramley** [comment]
This doesn't look correct. Currently the code in magic_quotes.php adds slashes when "magic_quotes_gpc" is false, which it always is for >= 5.4.
That code might be unnecessary or even wrong (as currently there is double escaping happening, such as a list name including a single quote is stored with a backslash in the database).

But removing the code needs testing of the fields that allow a single quote.

**Comment by michield** [comment]
Yes, this change needs thorough testing. But it's good to move that way. It will probably require fixing things.

**Comment by michield** [comment]
although, with hindsight, it may have been better to do this on a different branch first...

**Comment by michield** [comment]
I checked and Duncan, you're right, we'll need to put some of that code back. Going through all places that does stripslashes would be too much.

**Comment by oliverklee** [comment]
I'm on it.

**Comment by oliverklee** [comment]
I've just created PR #143 for re-adding the slashes to the request parameters.

**Pull request merged**
