### PR TITLE
Apply Alan George mod to the core of phplist to enhance email header …

### PR DESCRIPTION
**Pull request by utagawal**
…: https://www.alangeorge-photography.com/lcode_30x_14.php

### CODE REVIEW

**Comment by samtuke** [comment]
Thanks for this PR. What is the primary problem it is designed to solve? 

It seems to delete or comment out headers that already exist, only to move several of them to another part of the script. Additionally it adds some redundant comments to headers which already exists (labelling them as originating from the Alan George mod), which makes it harder to see the changes which are being introduced.

**Comment by samtuke** [comment]
The tests are failing due to this: https://travis-ci.org/phpList/phplist3/jobs/538287971#L651

**Comment by utagawal** [comment]
Hello, this allows to use mesag enveloppe preperly according to the Alan George Mod.

Then users acan unsubscribe directly by email reply.

Explanations are here on, why to implement this : https://www.alangeorge-photography.com/lcode_30x_14.php

Nxxt step is to have the bounce mechanism within phpList be able to process the unsubscribe requests.

**Comment by michield** [comment]
This PR is trying to do too many things at the same time. Some of the changes are simply said **disastrous** and cannot and should not be taken. I can comment inline for each of them, but I don't think that's worth the effort. Instead each element should be turned into a separate PR with the following structure:

1. problem that currently exists
2. explanation of the solution
3. reason for the related code change

**Comment by utagawal** [comment]
@michield wan you quickly point out the dissatrous changes at least to split the PR is only the relevant changes ?

**Comment by michield** [comment]
Maybe I was a little too dramatic. The only "disastrous" change is where message_envelope is removed. That will stop the bounce processing from working. As such, that is a bad idea.

Most of the other ones are just very "hacky". For example hard coding email addresses for "reply-to" and then like is just not the way to do things.

All in all, it's rather messy and as I wrote, it's better to split them into different PRs that each identify a problem and then resolve them.

**Pull request closed without merging**
