### PR TITLE
Tick all the checkboxes under a category when select all lists is ticked

### PR DESCRIPTION
**Pull request by MatheusHamonangan**
Hi there,

I've submitted an enhancement request in mantis https://mantis.phplist.com/view.php?id=17630, it has all the description there. Basically, I modified the phplist slighlty to suit my needs. I thought I might just share what I did and maybe it could help some people. Please let me know what do you think about the patch.

Thank you,

Matheus

### CODE REVIEW

**Comment by michield** [comment]
related to https://github.com/phpList/phplist-ui-dressprow/pull/9

**Comment by michield** [comment]
Any news from "legal"? Alternatively, you can mark your contribution as  MIT licensed by stating that here.

**Comment by MatheusHamonangan** [comment]
Hi Michiel,

I am really sorry for taking such a long time for this. So I've escalated
this issue to the director, I need to get his permission to sign the CLA so
I won't get into any trouble. I'll get back to you once I have feedback
from my director.  I really apologise for taking too long for making this
decision.


Regards,


Matheus

**Comment by michield** [comment]
the next version is planned for Aug 10 or about. Would be great to have this in.

**Comment by MatheusHamonangan** [comment]
Hi there,

Finally get the green light from the director :). I'll sign the CLA via
github. Sorry it took a while to get this sorted.


Cheers,


Matheus

**Comment by MatheusHamonangan** [comment]
Hi there,

I've signed the CLA, but it didn't give me any notification where it was
successful or not after form submit. Could you please check did the
signature fail or not?


Thanks,


Matheus

On Tue, Aug 4, 2015 at 10:36 AM, Matheus Hamonangan <matheusgultom@gmail.com
> wrote:

> Hi there,
>
> Finally get the green light from the director :). I'll sign the CLA via
> github. Sorry it took a while to get this sorted.
>
>
> Cheers,
>
>
> Matheus
>

**Comment by michield** [comment]
If you go to https://www.phplist.com/cla it should ask you to login with Github and allow the application. When you've done it, it should show you the date you did it.

**Comment by MatheusHamonangan** [comment]
Cool, I've signed it. Thanks

**Comment by michield** [comment]
Great, thanks!

**Pull request merged**
