### PR TITLE
Option to add password on the interface when you create a new admin

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=19061

### CODE REVIEW

**Comment by michield** [comment]
Can you make this enabled with a flag? I think we want to allow keeping the original way of working, which keeps the password more secret than then new one.

**Comment by xh3n1** [comment]
@michield Yes we can do that,  I would also prefer having a "confirm password" input. What do you think @michield @samtuke @suelaP ?

**Comment by michield** [comment]
Yes, confirm is good. You can also make it a single system, eg with divs/tabs

1. either use "send a password by email"
2. or input here

just like the compose campaign page being "input here" or "send a url"

**Comment by samtuke** [comment]
@xh3n1 My vote is with Suela.

**Comment by xh3n1** [comment]
I added the "confirm password" input field and some js for input validation:
Scenarios:

**if password is < 8** :

screen shot 2018-09-23 at 18 22 57

**if passwords do not match** :

screen shot 2018-09-23 at 18 23 41

**if password is >8 and passwords match**
  Note that "Save changes" button is **disabled** until this condition is met.
screen shot 2018-09-23 at 18 24 16

**Comment by samtuke** [comment]
Is this still on hold and work in progress?

**Comment by xh3n1** [comment]
@samtuke yes

**Comment by xh3n1** [comment]
@samtuke It's ready for review now. 
I was wondering why the js code for radio button was working on dressprow theme and not on trevelin, and then I found out that this: https://github.com/phpList/phplist-ui-bootlist/blob/18579645c28706b94e7a98297437050dae589439/js/phpList3ToBootstrap.js#L185-L190 was preventing it because the ID was changed to name+value attributes on DOM, making my ID not used. Anyway, I manually set the ID to the how the function would generate it. I will also add a PR for Dressprow theme.

**Comment by michield** [comment]
Reviewing the code, looks good. We should test this a bit though, once merged. 

But I'm happy with it, nice work!

**Pull request merged**
