### PR TITLE
Group lists by category feature 

### PR DESCRIPTION
**Pull request by xh3n1**
-https://github.com/phpList/phplist-ui-bootlist/pull/74 needs to be merged for lists to be split into two columns.

### CODE REVIEW

**Comment by xh3n1** [comment]
I will resolve merge conflicts.

**Comment by samtuke** [comment]
@xh3n1 Can you remove the extra margin at the bottom of lists? Currently they make the accordion section content have unbalanced whitespace at top and bottom of the section.
workspace 1_496

**Comment by suelaP** [comment]
We should change the following behavior: 
Currently if a Category has only private lists assigned to it will still be shown as a category in the front-end. 
We should only display categories that have at least on public list assigned.

**Comment by samtuke** [comment]
Currently the list name is repeated twice, and the list description isn't stated (when group by categories is used).
selection_498

**Comment by xh3n1** [comment]
@samtuke it's not the list name that's repeated, it's the description.

**Comment by xh3n1** [comment]
oh, i see what you mean, I'm checking now.

**Comment by xh3n1** [comment]
@suelaP it was happening only when lists were not selected on the subscribe page (all public lists displayed all by default), but I committed a change and it should be good now.

**Comment by xh3n1** [comment]
screen shot 2018-10-28 at 19 40 47

@samtuke I added the default setting on configuration page

**Comment by xh3n1** [comment]
@samtuke  I pushed a commit [here](https://github.com/phpList/phplist-ui-bootlist/pull/74) for the bottom margin.

**Comment by samtuke** [comment]
This feature in action (depends on changes to bootlist/trevelin theme also):

Per-list settings:
screenshot_2018-10-31 phplist 1

Global setting:
screenshot_2018-10-31 phplist

Example subscribe page single column:
screenshot_2018-10-31 subscribe to our newsletters 1

Example subscribe page dual column:
screenshot_2018-10-31 subscribe to our newsletters

**Pull request merged**
