### PR TITLE
Introduce Travis-ci and Behat testing

### PR DESCRIPTION
**Pull request by tarekdj**

### CODE REVIEW

**Comment by tarekdj** [comment]
@michield can you give it a review ?

**Comment by michield** [comment]
ah, nice. Yes, I'll try it out.

**Comment by michield** [comment]
it's all new files isn't it? Then it should be fairly safe to merge so that others can try it out. What do you think?

**Comment by tarekdj** [comment]
There is no integration with core code. It's an external component. Merge shoudn't cause any regression. Maybe I can add some doc to explain how to use it?

**Comment by michield** [comment]
yes, that would be great.

**Comment by tarekdj** [comment]
OK! Dont merge for now I'll add some doc

**Comment by tarekdj** [comment]
@michield I added the doc. PR is ready to merge

**Comment by michield** [comment]
nice!

**Pull request merged**
