### PR TITLE
Display campaign subject when clicking view campaign and fix the chrome tests failing 

### PR DESCRIPTION
**Pull request by xh3n1**
fix https://mantis.phplist.org/view.php?id=19197

### CODE REVIEW

**Comment by xh3n1** [comment]
also: https://mantis.phplist.org/view.php?id=19198

**Comment by michield** [comment]
what's the issue here. Why change from result to msgdata? One is pulled from the message table, the other from the message data.

Is this the "message subject" vs "campaign title" ? If that's the case, we should really display them both.

**Comment by xh3n1** [comment]
@michield before it was incorrectly displaying the campaign title instead of campaign subject.

**Comment by michield** [comment]
doesn't it make sense to display both? Something like;

campaign title
campaign subject line

**Comment by xh3n1** [comment]
Yes we should display both:
**Before** screenshot from 2018-04-26 22-52-47
**After:** 
screenshot from 2018-04-26 22-51-24

**Comment by michield** [comment]
Great :grinning:

**Pull request merged**
