### PR TITLE
check if the addons plugin is available and use it in preference to t…

### PR DESCRIPTION
**Pull request by michield**
…he updater.

## Description

If the addons plugin is available and enabled, use it as preference over the "updater" and link to it.

### CODE REVIEW

**Comment by michield** [comment]
@bramley can you review this? Then we can add it to the next release

**Comment by bramley** [comment]
I'm not sure about this change.
Firstly whether is a necessary to provide the link for updating, which is in the menu anyway, but  also referring directly to a particular plugin. A neater approach is to use the same method as for the editor plugin by identifying whether a plugin implements an interface. That way there isn't a direct reference to a specific plugin.

**Comment by michield** [comment]
Sure, that would make it more generic and allow other plugins to implement an "updater function". It'll be a fair amount of additional coding to make that construction. I'm worried that the existing updater throws people into maintenance mode without being able to get out of it, so I'd really like to retire the old updater.

Highly unlikely anyone would contribute some additional plugin for updater though, so this would for now be sufficient.

As for the notification here, this will only show when there's an update. The link in the menu is always there, and people wouldn't go and check all the time.

**Comment by bramley** [comment]
Wasn't so much code after all, see https://github.com/phpList/phplist3/pull/946

**Comment by michield** [comment]
superseded by #946

**Pull request closed without merging**
