### PR TITLE
Removed obsolete references for Mantis

### PR DESCRIPTION
**Pull request by lwcorp**
Removed obsolete references

### CODE REVIEW

**Comment by michield** [comment]
Thanks. It's not really a code change, so I've marked it ready to merge, but if you can [sign the CLA](https://www.phplist.com/cla) anyway, that would help with future contributions.

**Comment by lwcorp** [comment]
Done, but I'm pretty sure I've signed up prior to my previous PRs, so why did I need to resign?

**Comment by michield** [comment]
Great, thanks. Was that with this account? Because I didn't see your handle in the list. It's there now, thanks

**Comment by lwcorp** [comment]
I assume it was this account, as see [my past (accepted) PRs](https://github.com/phpList/phplist3/pulls?q=is%3Apr+author%3Alwcorp+is%3Aclosed).

**Review by marianaballa — APPROVED** [review]

**Pull request merged**
