### PR TITLE
Move required extensions in checkprerequisites.php file and removed some optional ones

### PR DESCRIPTION
**Pull request by xh3n1**
- Moved required extensions in checkprerequisites.php.
- Removed some optional ones such as gd, iconv, mbstring etc

### CODE REVIEW

**Comment by bramley** [comment]
It might help if you can explain how you came to decide which extensions are mandatory and which are optional.

Previously I explained that curl is currently optional, in that phplist code tests whether it can be used, see the comment by Michiel https://mantis.phplist.org/view.php?id=19838 on how to simplify fetching a remote URL.
I think that my original point in https://mantis.phplist.org/view.php?id=19838 has not really been addressed. What I am concerned about is an upgrade to phplist breaking someone's installation.

**Comment by samtuke** [comment]
curl should be removed from the list of required extensions in this PR, because the other recent PRs which rely on it have been, or are being, updated with fallbacks. fetchURL() is indeed a useful, centralised workaround for installations without it - the fact it uses caching is an added bonus. Thanks for pointing this out @bramley.

In the near future I think it makes sense to make curl a required extension, because it has been included in standard distributions of PHP for some time and is very widely used. fetchUrl() is useful but won't serve as a replacement in all scenarios, eg more complex cases where authentication, redirection, or other curl features are required. For 'developer experience' it is awkward to keep track of which default PHP extensions are required by PHP or not. Therefore while fallbacks for all uses of curl will be in place for the next phpList release, I propose making curl required in the following months, and giving notice to phpList users that this change will take place. Hopefully this would only impact a small number of users.

@bramley What's your view?

**Comment by samtuke** [comment]
@bramley Any objections to this being merged?

**Comment by bramley** [comment]
I agree with validating that those extensions which are used unconditionally in the code are installed. This list looks ok but I don't know if there are any more.

**Comment by samtuke** [comment]
@bramley Thanks for the feedback. Yes probably there are more, and they can be added to the list as they are discovered.

**Pull request merged**
