### PR TITLE
Move tabs from userhistory to user by using ajax

### PR DESCRIPTION
**Pull request by xh3n1**
[Create fallback handling for jQuery UI async tabs](https://github.com/phpList/phplist-ui-bootlist/pull/59) needs to be merged to make it work.
On this PR I have:
1. created a page on actions folder for each element of userhistory. 
2. removed the userhistory button and replace every userhistory pagelinkbutton with user.
3. changed the confirm button to use an event handler because script tags are not executed on while loaded async.

I'm not sure about permission checks on the newly created pages. Any feedback?

Signed-off-by: Xheni Myrtaj <myrtajxheni@gmail.com>

### CODE REVIEW

**Comment by xh3n1** [comment]
screen shot 2018-06-26 at 13 06 09

**Comment by xh3n1** [comment]
I will also fix the tests.

**Comment by samtuke** [comment]
@xh3n1 When clicking the following tabs: Campaigns, bounces, Subscription, I get the following error:

```
Error: Syntax error, unrecognized expression: ./?page=pageaction&action=campaigns&ajaxed=true&id=1&tk=9f03275d26431f47f63612383fc3a689 jquery-1.12.1.min.js:2:12733
	t</fa.error http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:12733
	t</fa.tokenize http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:18785
	t</fa.select http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:21596
	fa http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:7320
	find http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:24109
	n.fn.init http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:24672
	n http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:406
	c.prototype.show http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/dist/phpList_ui_bootlist.min.js:5:25871
	b/< http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/dist/phpList_ui_bootlist.min.js:5:25372
	each http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:2879
	each http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:2:844
	b http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/dist/phpList_ui_bootlist.min.js:5:25264
	e http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/dist/phpList_ui_bootlist.min.js:5:26887
	dispatch http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:3:12396
	add/r.handle http://local.pl2/lists/admin/ui/phplist-ui-bootlist/js/jquery-1.12.1.min.js:3:9158
```

**Comment by xh3n1** [comment]
@samtuke did you use this https://github.com/phpList/phplist-ui-bootlist/pull/59?

**Comment by samtuke** [comment]
@xh3n1 No; and with that branch of the theme the problem is resolved. Thanks for the hint

**Comment by samtuke** [comment]
@xh3n1 I see that you removed the test for the userhistory pages from `newsubscriber.feature`, but it looks like replacement tests were not added (so the subscriber history data is no longer checked). Can you add some corresponding tests?

**Comment by michield** [comment]
Ok, both PRs merged. Will be good to do some thorough testing on this.

**Pull request merged**
