### PR TITLE
Update to current version of french translation

### PR DESCRIPTION
**Pull request by roms2000**

### CODE REVIEW

**Comment by michield** [comment]
@roms2000  please sign the [CLA](https://www.phplist.com/cla) to allow me to merge

Also, there's not really a need to merge this, as the languages are managed differently. However, it won't harm either.

**Comment by michield** [comment]
If the changes are significantly different from the existing translation, they will be overwritten from the translate.phplist.org site. How did you create this .po? Shall we import it into the translate.phplist.org site, so that it is retained.

**Comment by roms2000** [comment]
CLA has been signed.
For translation / po file, this was an export from translation.phplist.org.
So no need to force rewrite as you suggest.

**Comment by michield** [comment]
Ok, thanks. In that case, I'll close this. The translation from translate.phplist.org is automatically used in new releases and when users update the translations from inside the application.

**Pull request closed without merging**
