### PR TITLE
Stats overview formatting

### PR DESCRIPTION
**Pull request by samtuke**
- Replaced $GLOBALS['I18N']->get() with s()
- Added number formatting to stats (cast vars to int and then apply number_format() )
- Changed col heading 'views' to 'unique views'

### CODE REVIEW

**Comment by samtuke** [comment]
@suelaP This changes the column heading as requested

**Comment by michield** [comment]
in the light of the trouble we had with number_format on the account pages, I'd stay away from using that, but if you insist and accept the risk, I'm happy to merge it.

**Comment by samtuke** [comment]
@michield Did you get to the bottom of why it was returning empty before? I presume it was because a variable which could not be converted into a number was provided to it. Number formatting is something that cannot be avoided, so either we need to use function or another one (write a new one?). I don't recall problems with this function except for that particular recent case.

**Comment by michield** [comment]
No, I still don't know why that happened. I will need to investigate a bit more before I can merge this.

**Comment by michield** [comment]
Let's take it and update it later

**Pull request merged**
