### PR TITLE
Copy to draft feature

### PR DESCRIPTION
**Pull request by rolanyang**
The request comes up every now and then for the ability to copy a previously sent message into draft.
This adds a button in the "Sent" campaign list to do so.

https://forums.phplist.com/viewtopic.php?p=39364

Updated the patch to work with the latest version.

Would be nice if this could be coded as a plugin, but there isn't a hook for it yet.

https://mantis.phplist.org/view.php?id=19263

### CODE REVIEW

**Comment by samtuke** [comment]
Brilliant - thanks for the PR 👍 It should be reviewed shortly.

**Comment by michield** [comment]
Yes, this has been requested many times. I have always been hesitant to add something like this, as I think it will make it easier to accidentally duplicate content to subscribers. 

My preference would be to wrap this in a config option that can be enabled in the config file, but is not enabled by default. We can then warn about it in the comments on the config file.

**Comment by samtuke** [comment]
How about adding contextual help or a popup to the button to warn not to send duplicate content to subscribers?

**Comment by xh3n1** [comment]
Great PR, 
just one small fix: could you please use a copy icon instead of edit?
photo_2018-05-31_21-07-40

**Comment by michield** [comment]
@rolanyang before we can merge PRs from you, could you [sign the CLA](https://www.phplist.com/cla)? Thanks

**Comment by rolanyang** [comment]
CLA done. 
I was looking for an icon closest to copy in ui/dressprow/images/16x16
It was either edit-1.png or library.png

One more thing to look over: 

I don't know what the database fields  repeatinterval, repeatuntil, requeueuntil, requeueinterval do. Perhaps it might be better to leave them out of the "insert" query. Also I'm noticing now that "processed" should probably be left out as well.

**Comment by samtuke** [comment]
I think the fontawesome catalogue of icons should be at your disposal as well.

**Comment by michield** [comment]
You may want to check out the repeatMessage function 

https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/connect.php#L1811

This is used when REPETITION is enabled and campaigns and automatically duplicated after they have been sent. 

To make this feature work fully, you would need to duplicate attachments as well.

You won't be able to use that function, but you can verify the steps done there.

**Comment by rolanyang** [comment]
In regards to using the "copy" icon, implementing would cascade changes down into the bootstrap.js, and a slew of css files one for each of the themes. The 16x16 image would have to be extracted out of the glyph's file too as Dressprow theme doesn't use woff2 fonts for the buttons.  I'm not sure if you want to go down that route.

**Comment by samtuke** [comment]
I copied this branch and created a PR which replaces the edit icon with a copy one: https://github.com/phpList/phplist3/pull/342

**Comment by rolanyang** [comment]
Are there any remaining tasks that need to be done on my part?

**Comment by samtuke** [comment]
@rolanyang What about campaign attachments? Did you take a look at the logic for campaign repetition that michield mentioned?

**Comment by bramley** [comment]
This is missing some fields on the message table - uuid, repeatinterval and requeueinterval.

Several fields are held on the messagedata table, not on the message table - finishsending, sendmethod, sendurl, campaigntitle and excludelist, so those should be copied too.

I think that people will expect the new draft message to be sent to the same lists as the original, so the rows on listmessage for the original should be also be copied.

See https://github.com/bramley/phplist-plugin-common/blob/master/plugins/Common/DAO/Message.php#L36 for how I implemented similar function for the Campaigns plugin.

**Comment by rolanyang** [comment]
In testing, I noticed the Campaign Subject would be lost and instead take on the Campaign Title unless the "subject" field was copied over in the phplist_messagedata  table.

**Comment by michield** [comment]
how does this relate to #342 ?

**Comment by samtuke** [comment]
#342 Makes an icon available for the "duplicate" action. Any button can use the button by using the corresponding css class.

**Comment by samtuke** [comment]
@rolanyang Are you able to fix that so the subject isn't lost?

**Comment by rolanyang** [comment]
The most recent commit fixed the lost subject issue.
https://github.com/phpList/phplist3/pull/340/commits/cd82b727bd31025c54f76f4751fc1364e461fc85

**Comment by michield** [comment]
@samtuke good to go for me, if we ensure some testing is done

**Comment by michield** [comment]
@samtuke do you want to remove the wip label? or is there still something outstanding. I actually think that not copying the attachment may be a good thing, otherwise you could end up accidentally sending the same attachments. In a way, that was the reason I was never in favour of a feature like this, but as a minimal implementation I guess it will improve UX a little.

**Pull request merged**
