### PR TITLE
Add Updater repository to Travis

### PR DESCRIPTION
**Pull request by suelaP**
Add the Updater Repository to the Travis set up

Mantis: https://mantis.phplist.org/view.php?id=19924

To be merged after changes to https://github.com/phpList/updater/pull/75 are made.

### CODE REVIEW

**Comment by samtuke** [comment]
Tests failing with:

```
Failed: ./public_html/lists/updater/index.php
PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in ./public_html/lists/updater/index.php on line 19
```

**Comment by suelaP** [comment]
They are supposed to fail as they detect the un unsupported syntax in php 5.3 and 5.4. 

When The fix from Xheni is merged they will pass.

**Comment by samtuke** [comment]
@suelaP OK great

**Comment by suelaP** [comment]
This can be merged now

**Comment by samtuke** [comment]
Reviewing this again, wouldn't it be better for the updater tests to be in the updater repo, so that commits there which change its behaviour result in failed builds for that repo, and not this one? Otherwise failed builds in this repo may mean changes were made elsewhere, and PRs to the updater repo will always pass, regardless of issues introduced.

**Pull request closed without merging**
