### PR TITLE
Add Pop-Before-Smtp Connection

### PR DESCRIPTION
**Pull request by jd440**
On server accepting only pop-before-smtp, this patch allowed to mail

### CODE REVIEW

**Comment by bramley** [comment]
According to wikipedia pop before smtp has been superceded by SMTP authentication https://en.wikipedia.org/wiki/POP_before_SMTP so I wonder why you need to use it.

**Comment by jd440** [comment]
I got a server using it and i could connect otherwise.
But for sure if i'm the only one we can close it.

**Comment by samtuke** [comment]
@jd440 Like @bramley, I also wonder why this is still necessary. However the patch is straightforward and others may experience the same problem.

@michield @bramley Do you see any problem in including this patch?

**Comment by bramley** [comment]
One slight problem is that only jd440 is able to test this and confirm that it works.

Also, I didn't like adding several extra config values, that seems to be cluttering the config file. The way that pop before smtp seems to differ from the usual smtp is that the authentication is done as a separate step, otherwise it is standard smtp.

 So I would be inclined to make this an option within the existing smtp processing and re-use the existing smtp fields - PHPMAILERHOST, username, password etc. Roughly something like this

```
        global $phpmailer_smtpuser, $phpmailer_smtppassword; // and any other config variables
...
        } elseif (defined('PHPMAILERHOST') && PHPMAILERHOST != '') {
            if (defined('PHPMAILERPORT')) {
                $this->Port = PHPMAILERPORT;
            }
            //logEvent('Sending email via '.PHPMAILERHOST);
            $this->Host = PHPMAILERHOST;

            if (POP_BEFORE_SMTP) {
                // authenticate using the smtp user and password
                $pop = new POP3();

                if (!$pop->authorise(PHPMAILERHOST, 110, 30, $phpmailer_smtpuser, $phpmailer_smtppassword, 1)) {
                    // unable to authenticate, there might be an error message in $pop->getErrors()
                }
            } else {
                // the existing smtp code
                if (isset($GLOBALS['phpmailer_smtpuser']) && $GLOBALS['phpmailer_smtpuser'] != ''
                    && isset($GLOBALS['phpmailer_smtppassword']) && $GLOBALS['phpmailer_smtppassword']
                ) {
                    $this->Username = $GLOBALS['phpmailer_smtpuser'];
                    $this->Password = $GLOBALS['phpmailer_smtppassword'];
                    $this->SMTPAuth = true;
                }
            }
            $this->Mailer = 'smtp';
...
```

**Comment by jd440** [comment]
As request by @bramley, Re-use smtp fields

**Comment by bramley** [comment]
My bit of code was just an example, not intended to be copied without changing it. I would not expect this change to actually work

- need to include error handling
- the name of the config setting POP_BEFORE_SMTP, use '_' to separate words
- use true or false instead of 0 or 1 but definitely not ''

**Comment by samtuke** [comment]
@jd440 Is this ready for review?

**Comment by bramley** [comment]
The code still needs corrections and tidying-up, but I'm not really sure that this functionality needs to be added.

@jd440 please can you explain why you need to use the "pop before smtp" method and what other methods are available for sending? Who is the hosting company that you use?

**Comment by jd440** [comment]
hey @bramley please don't make me lost my time.
I close this PR 27 days ago after your first comment.
You ask me many correction. and after 1month spending time just to offer this PR you asking one more time if yes or not this PR is needed to be added.

I need it.
I'm using it for years on my side, i thought it could interest some others even if I'm agree with you Pop-before-smtp is almost dead.
You don't want to integrate it… Fine
But start to think if you want to integrate it before ask me corrections.


I'm disappointed… one month ago when I started to commit I was very enthousiatic…
Now I just got feeling to lost my time.

**Comment by samtuke** [comment]
@jd440 There's no need to close the pull request; @bramley was just asking for more information about your use case.

From my perspective, the feature is not complex, and so long as it meets coding guidelines then the added option is worth having.

I'm not sure that including optional debugging output is necessary though.

**Comment by bramley** [comment]
@jd440 apologies, my previous comment wasn't helpful for your change.

**Comment by jd440** [comment]
ok So what would you need to merge it?

**Comment by michield** [comment]
Considering it's wrapped in a config option, it seems fairly safe to merge. It would be good to document the new config options in https://resources.phplist.com/system/config

**Pull request merged**
