### PR TITLE
 Add info buttons to headings on stats overview page

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=18725

### CODE REVIEW

**Comment by xh3n1** [comment]
Please, do not merge this one yet. I have to investigate something first.

**Comment by samtuke** [comment]
OK!

**Comment by samtuke** [comment]
@xh3n1 Is this still blocked?

**Comment by xh3n1** [comment]
It's fixed now. You can review and merge.

**Pull request merged**
