### PR TITLE
0019187: Add draft campaign for use with invite plugin available in new installations

### PR DESCRIPTION
**Pull request by xh3n1**
https://mantis.phplist.org/view.php?id=19187

### CODE REVIEW

**Comment by bramley** [comment]
@xh3n1 Is this something that you have been discussing with Sam and Michiel already? Is the Invite plugin going to be included within phplist now?

**Comment by bramley** [comment]
I'm not sure that I want phplist to automatically create a draft campaign, which I would likely then just delete.

The main saving by this change appears to be providing some default content for an invite campaign, as creating a draft campaign is trivial anyway.
Maybe that default content could be provide in some other way, e.g. when you select "invite" on the Format tab then the plugin could populate the message content with the default content but only if the message content has not already been entered. The plugin could then provide a config setting for the default content, which allows someone to customise and translate it and reuse that content for several invite campaigns.

Also you need to consider other languages than English, otherwise the content has to be changed anyway. And it should probably be in html rather that plain text. The Mantis attachment is html but this change appears to be plain text.

**Comment by samtuke** [comment]
@bramley Great points.

1. The campaign may just be deleted - true, however there is no downside to having an extra draft except for clutter, and the benefit of having an easy way to use re-opt-in campaigns is worth the inconvenience.

2. Insert the campaign content after 'invite' format is selected - good idea, though having to go past the first page(s) where subject and content are set to get to the 'format' tab and select 'invite' is not intuitive. Also this would add complexity to the invite plugin, which is doable, but would likely delay the availability of the default campaign in any format before May 25th. Making the content reusable in this way would be superior to the draft campaign, which will no longer be a draft following its first use.

3. The content is not translatable - yes that is currently a problem. The standard s() function could probably be used as with other translatable strings, but this is not yet the case. The English version should be final before this to avoid wasted efforts of translations in later editing. Do you have feedback on the current campaign content?

4. Campaign content should be HTML - agreed. @xh3n1 Can you add an HTML version as well? It should only require basic markup such as paragraphs, but without that it will render in monospace on some mail clients, and HTML templates will not be used.

@bramley In conclusion I propose that the invite plugin is bundled with phpList 3.3.3, and this campaign is included in core as Xheni has already implemented, with HTML and translatable content, and that we mantis an improvement for making the content reusable, potentially inserting the content automatically following selection of 'invite' on the format tab. This approach allows the invite campaign to be included in phpList 3.3.3 with minimal additional work in time for its release very soon. What do you think?

**Comment by bramley** [comment]
How about a different approach. 
Presumably people will look at the plugin documentation https://resources.phplist.com/plugin/invite and https://github.com/michield/phplist-plugin-invite to understand what it does and how to use it. So you could include sample content in the documentation, which can then simply be copy/pasted into a new campaign in phplist.

But anyway the documentation should be improved if the plugin is going to be mass distributed in this way. I suggest moving the usage guidance from the readme in GitHub to the documentation page. In that way the documentation and guidance can be revised separately to the plugin code.

I have installed the plugin for a couple of people, and both times it was a bit confusing as how best to use it in terms of which lists to create or add people to. There are probably a few common scenarios

- a reminder to people who have not confirmed their subscription
- a GDPR type message asking confirmed subscribers to accept a new privacy policy
- chasing confirmed subscribers who have been inactive for a while

so maybe there could also be some guidance on how best to handle these.

**Comment by samtuke** [comment]
@bramley Yes the plugin documentation should be improved either way. However I think it is unlikely that most admins will ever go to the plugin docs page, especially when the plugin is bundled by default. It would be good to add contextual help using a (?) button on the 'Format' page so that an explanation is closer at hand.
Regarding the four scenarios, documentation of each would be good but I'm not sure of the best place for that. Perhaps the manual is the best place for it.
Overall this PR is an imperfect solution, but it makes it significantly easier to use functionality that many are seeking due to GDPR. I would like to merge this now in order to have an easy path to 'repermission' campaigns released before May 25th. Moving this draft into the Invite plugin itself seems like a good step to follow up with after releasing  phpList 3.3.3.

**Comment by samtuke** [comment]
@xh3n1 Is it possible to add a meta title to the campaign which communicates to the admin what the campaign is for (besides the campaign subject for the message recipient)? E.g. 'Example re-permission campaign'

**Comment by michield** [comment]
I think this is a good idea. It's often considered useful to have some examples in the draft queue and they can be ignored or deleted, so won't affect anything.

**Pull request merged**
