### PR TITLE
Mantis 17290 - Predictable embargo time when periodically requeuing a message

### PR DESCRIPTION
**Pull request by bramley**
This pull request changes the way that the new embargo time is calculated when a message is requeued.
It adds a multiple of the requeue interval to the current embargo so that the new value is in the future, i.e. greater than the current time. The benefit of this is that the embargo time is then predictable, e.g. every day at 08:00, instead of drifting forward as it now does.

The sql looks a bit complex but the underlying algorithm is straightforward

* calculate the number of requeue intervals between the current embargo and now - this will usually be between 0 and 1 unless the queue processing has been delayed
* truncate to an integer and add 1
* multiply by the requeue interval
* add to the current embargo

This results in the earliest time in the future that is consistent with the current embargo and the requeue interval.

The online help also needs to be changed (I have a revised version) but I don't know how that is managed.

### CODE REVIEW

**Comment by michield2** [comment]
The contents of the help is here: https://github.com/phpList/phplist-lan-help

**Comment by bramley** [comment]
So I should just fork that repository in the same way as for the phplist3 respository? If I change some of the English text, how will that get translated into other languages?

**Comment by michield** [comment]
Yes, you can fork that repo and do PRs for it. Translations work the same way (forking and PRs).

**Comment by michield** [comment]
:+1: reading the SQL makes me dazzle :-) but I guess if it works in your setup as you describe, then it'll be great improvement.

**Pull request merged**
