### PR TITLE
Not send email confirmation

### PR DESCRIPTION
**Pull request by jd440**
Continuation of PR200

### CODE REVIEW

**Comment by bramley** [comment]
Settings that are on/off are probably better defined using true/false rather than 0/1, which simplifies the code just a little bit, e.g.

`if (UNSUBSCRIBE_CONFIRMATION) {`

A couple of layout points

- use spaces instead of tabs
- a space each side of any operator, such as "="

**Comment by jd440** [comment]
Thanks for you review! correction done

**Comment by bramley** [comment]
The comment line in config_extended.php about setting to 0 is now incorrect.

But that raises a point about config_extended.php. I think that it is intended to match config.php plus all the default values applied in init.php.
So the setting should be to true not false, with the comment line explaining how to turn-off the setting.
This might also apply to the other pull requests.

**Comment by bramley** [comment]
I think that you have misunderstood my previous comment. You have now made the default behaviour to not send the unsubscribe confirmation email whereas it is currently sent. There is no need for the setting to be in config.php, and should not be there, if a default value is set in init.php.

- don't change config.php, or at least only after a discussion about phplist default behaviour
- the setting in config_extended.php should match the default value that is set in init.php. That allows someone to swap config_extended.php and config.php when installing without any surprises.
- the comment in config_extended.php should explain how to change the default setting

**Comment by jd440** [comment]
ok. i think this time i understood what you mean.

**Comment by jd440** [comment]
what do you think about last commit?

**Comment by michield** [comment]
Yes, looks good. jd440, if you can [sign the CLA](https://www.phplist.com/cla), I can merge this

**Comment by jd440** [comment]
I did already sign it, and one of my PR(204) have already been merged?

I signed et again

> Awesome, you have signed the phpList CLA
> Your github login: jd440
> Your name: jean
> Date signed: 2017-11-23

**Comment by michield** [comment]
strange somehow your previous signing had gone lost. Many thanks!

**Pull request merged**
