### PR TITLE
Removed symlinks which go to non-existent directories on local machines

### PR DESCRIPTION
**Pull request by samtuke**
Do these symlink serve a purpose? On my local machine, their existence means that real copies of themes are deleted each time changes are stashed and code is pulled. Even using git stash save -u does not prevent real theme files from being deleted, as these symlinks always overwrite the directories.

### CODE REVIEW

**Comment by michield** [comment]
Hmm, this will break our dev server. I understand why you want this, but it's a bit tricky to sort out. Easier is to add the symlinks on your local machine to your repos. The reason for the  symlink is to have the repos outside of each other, and not be git modules.

**Comment by samtuke** [comment]
If the symlinks are only useful to the dev server, perhaps they could be added locally there, and the .gitignore file could have entries added to ignore those files (that would be useful for prevent unintentional adds or commits of themes on local dev copies also). Thoughts?

**Comment by michield** [comment]
Yes, good point. I've added all of "ui" to the ignore, so that it can be set locally

**Comment by samtuke** [comment]
Great - thanks!

**Comment by michield** [comment]
I guess now I should fix this: http://dev.phplist.com/lists/admin/

**Pull request merged**
