### PR TITLE
try to make poweredby logo adjustable to screen size.

### PR DESCRIPTION
**Pull request by mariez**
I could't  test it on my local copy. I want to see it in dev site to access from different screens

### CODE REVIEW

**Comment by michield** [comment]
github did not allow me to merge, but I've done it manually.

**Comment by bramley** [comment]
This change seems to have caused  a problem when the image is displayed in Outlook.

https://discuss.phplist.org/t/powered-by-image-too-large-version-3-2-5/1859

**Comment by mariez** [comment]
i will check it

**Comment by mariez** [comment]
This should fix that:
https://github.com/phpList/phplist3/pull/69/commits/8cb1bbbebef57c5f50d0c10807ecf049dabc6c3b

**Pull request closed without merging**
