### PR TITLE
Ajax fail do500

### PR DESCRIPTION
**Pull request by maltfield**
added a call to explicitly set the http response code to 500 per my previous PR:

 * https://github.com/phpList/phplist3/pull/432

### CODE REVIEW

**Comment by maltfield** [comment]
ugh, can someone explain to me why this PR has commits from my other PR in it? I intentionally put them in distinct branches to prevent this :(

 * https://github.com/phpList/phplist3/pull/444

Distinct branches:

 * https://github.com/maltfield/phplist3/tree/hackAttemptFix
 * https://github.com/maltfield/phplist3/tree/ajaxFailDo500

**Comment by bramley** [comment]
Does this change do what you intend, or at least are you sure that it does something different to before the change? 
When an exception is thrown the immediately following code will not be executed. If you want to explicitly return a 500 status code then you don't want to throw an exception, which I think was the gist of my comment on the previous change.

**Comment by xh3n1** [comment]
@maltfield try doing git reset or creating a new PR and cherry pick the commit that you want.

**Comment by samtuke** [comment]
@maltfield git cherry pick also allows you to pick a range or commits -- it's great that way. Extricating the commits you want should only take a few git commands to do.

**Comment by xh3n1** [comment]
@maltfield Anything I can do to help you here? :)

**Comment by samtuke** [comment]
It would be good to get this merged before branches diverge further

**Comment by maltfield** [comment]
Sorry, I feel like a total git, but I have no idea how to do this. Why would my PR include multiple branches? Shouldn't the commits between branches be isolated? I thought that was the point of branches..

Here is my change

```
user@personal:~/sandbox/phplist3$ grep -C10 "FAIL" public_html/lists/index.php 
                    if (empty($confirmation)) {
                        echo 'OK';
                    } else {
                        echo $confirmation;
                    }
                    exit;
                } else {
                    // we failed to subscribe the user; send an error back to
                    // the ajax client

                    echo 'FAIL';

                    // log an error and set the http status code to a 500
                    // Internal Server Error, easily caught by jquery.ajax()
                    error_log( "Error: Subscribe attempt failed!" );
                    http_response_code( 500 );

                }
                break;
            case 'preferences':
                if (!isset($_GET['id']) || !$_GET['id']) {
user@personal:~/sandbox/phplist3$ 
```

It looks like it comes from commit = 5f5274dc704524bc7d3afd6b4d2d2d16dee294f8 = https://github.com/phpList/phplist3/pull/445/commits/5f5274dc704524bc7d3afd6b4d2d2d16dee294f8

I tried to cherry pick it, but it says there's no changes to commit..


```
user@personal:~/sandbox/phplist3$ git cherry-pick 5f5274dc704524bc7d3afd6b4d2d2d16dee294f8
On branch ajaxFailDo500
You are currently cherry-picking commit 5f5274dc.

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
user@personal:~/sandbox/phplist3$ 
```

What do you need me to do here?

**Comment by michield** [comment]
This is now done here https://github.com/phpList/phplist3/commit/68a37581c0ae119b18e41a3f6dfbb3eb2a37ae9c

**Pull request closed without merging**
