### PR TITLE
Mantis20221 fix bug

### PR DESCRIPTION
**Pull request by michield**
## Description
Fix bug when selecting all lists or all public lists on the exclude element in the list selection

## Related Issue
https://mantis.phplist.org/view.php?id=20221

### CODE REVIEW

**Comment by suelaP** [comment]
@michield  the selection of lists on "list exclude" isn't working as expected. 
When I select a list to exclude and I click "Save draft" or "Save and continue editing" I should be able to check the lists I selected but that doesn't happen after the changes.

**Comment by michield** [comment]
Yes, I see what you mean. I'll look into it.

**Comment by michield** [comment]
@suelaP this should work correctly now.

**Comment by suelaP** [comment]
@michield list information is now saved but there is an empty  "@"  tab still available. See screenshot:
photo_2020-07-03_15-26-37

**Comment by michield** [comment]
Yes, for now that will have to stay. It's cosmetic, and necessary for it to work. Without it, you can't "uncheck all" lists.

**Pull request merged**
