### PR TITLE
Amended loading wait time messages for ajax actions

### PR DESCRIPTION
**Pull request by samtuke**
Fixed initial messages which were just temporary

### CODE REVIEW

**Comment by samtuke** [comment]
As these messages are reusable between pages, it would be good to centralised them rather than duplicate the content as they are used in an increasing number of pages in future.

**Comment by michield** [comment]
Kind of. In some places they say different things, but yes, I'll make the default to be central and  then allow overriding per page

**Comment by michield** [comment]
there's no point repeating the same message, as you did "Content loading". That won't be visible. Then we can just as well not have the message. I also don't like "Thank you for your patience", particularly not so early in the process.

**Comment by michield** [comment]
ok, I'm redoing this to use one single function with generic texts. Will be much easier

**Comment by michield** [comment]
It's moved here: https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/lib.php#L2155

**Pull request closed without merging**
