### PR TITLE
Travis Selenium Integration

### PR DESCRIPTION
**Pull request by kilip**
This note can be found in [this gist](https://gist.github.com/kilip/5aaae72d7f5dde63caf561c1eb85b92a)  too.
### New Development Requirements
To make selenium easier to be used by developer this 2 packages added into dev dependencies:
- `enm1989/chromedriver`
- `se/selenium-server-standalone`

New bash script `bin/start-selenium` added, so developer can start selenium by using this command:
```bash
# cd path/to/phplist3
$ bin/start-selenium
```

This command need to be execute before perform behat tests with `chrome` browser

### Parameters Changed
This config parameters for `FeatureContext` is deleted:
- baseurl
- db_user
- db_password
- db_name
- admin_username
- admin_password

The new config`FeatureContext` parameter with their default value is:
```yaml
# cd path/to/phplist3/behat.yml
default:
    suites:
        default:
            contexts:
                - FeatureContext:
                    # Set database access credentials
                    database:
                        host: localhost
                        user: phplist
                        password: phplist
                        name: phplistdb
                    # Set admin user login credentials
                    admin:
                        username: admin
                        password: admin
```

### Browser Testing
By this default command behat will be using goutte:
```bash
$ behat
```
To do tests with chrome browser we should type this command (using behat profile):
```bash
$ behat -p chrome
```
Since using selenium with firefox is buggy, we can't tests firefox browser (at least for now).

### Travis Build
- Removed php **5.3** version, because no compatible package availble for php 5.3 version to take a screenshot during selenium tests.
- Actually the old travis build never use the phpenv version, the php version used in test is the one from apache (see this [link](https://github.com/phpList/phplist3/blob/6187a3fd852dfc403806fc42b46ade4cb1e9f885/.travis.yml#L13). In the new travis configuration we using php built in server:
```bash
$ php -S localhost:8000 -t public_html/
```
- By default all tests in php version will use goutte, we only have 7.1 version to be tested with chrome browser
- For chrome browser test, failed screen shot will be uploaded into imgur by using `bin/imgur-uploader.sh` script. A link for this image can be found by the end of travis build log
- Behat will skip features/scenarios that tagged with `@wip` such as [this feature](https://github.com/kilip/phplist3/blob/e51c919a975ee2b32e139b2a551a711902ed5aea/tests/features/managing-campaigns/newcampaign.feature#L2). Please remove this tag if that features/scenario is fixed.

### CODE REVIEW

**Comment by samtuke** [comment]
@kilip Please can you resolve the conflicts so that this can be merged?

**Comment by bramley** [comment]
I was a bit puzzled why this includes unrelated commits going back to October. Possibly you have been using a very old branch. It might be clearer to rebase using the current phplist master so that only your changes on February 6 are committed.

**Comment by michield** [comment]
@samtuke there are no conflicts, but not all tests passed. I think that may have been Travis. I restarted the one failing job to see if that helped.

**Comment by michield** [comment]
@bramley I think @samtuke  can explain more about the history, but I do think this branch goes back to October.

@samtuke @kilip the restarted job still fails. It fails on one test "52 scenarios (51 passed, 1 failed)"

And only on Chrome on PHP7.1

Question for @kilip how do we access the screenshots that are taken?

**Comment by samtuke** [comment]
@michiel the conflicts were resolved earlier today by @kilip.
@bramley this branch is forked from behat-cleanup, so the commit is likely in that branch; I'm not sure which one or why. I tried rebasing this branch on master today without success.

I'm looking forward to trying the tests locally tomorrow.

**Comment by kilip** [comment]
@michield , @samtuke 
Forgive me if I am wrong, I have merged master into this behat-cleanup branch first, before I make a pull request.

#### Screenshot
`bin/imgur-uploader.sh` start to upload scripts in [this line](https://travis-ci.org/phpList/phplist3/jobs/338069074#L702), and it will creating output like:

`build/screenshot/tests_features_managing-subscribers_newsubscriber_feature_6.png: https://i.imgur.com/YVPTDTw.png`

In that case the screenshot can be found on: https://i.imgur.com/YVPTDTw.png

#### Failed tests
As I mentioned earlier, travis will ignore features/scenario that tagged with `@wip`. So actually we have 2 test that still need work:
skipped feature: `newcampaign.feature` [source](https://github.com/kilip/phplist3/blob/e51c919a975ee2b32e139b2a551a711902ed5aea/tests/features/managing-campaigns/newcampaign.feature#L1)
failed feature: `newsubscriber.feature` at this [step](https://github.com/kilip/phplist3/blob/e51c919a975ee2b32e139b2a551a711902ed5aea/tests/features/managing-subscribers/newsubscriber.feature#L8)

**Comment by samtuke** [comment]
@kilip Thank you for merging master; that makes it possible to merge more quickly.
I have merged this into behat-cleanup in order for others such as myself to be able to push changes.
The test you mentioned, newsubscriber.feature, has been fixed and is passing locally and on Travis.

**Pull request merged**
