### PR TITLE
Increased email address crop limit to 35

### PR DESCRIPTION
**Pull request by samtuke**
This makes better use of available screen space using both Dressprow and Trevelin themes, also on mobile devices

### CODE REVIEW

**Comment by samtuke** [comment]
phplist phplist view opens - nightly_317
phplist phplist view opens - nightly_316

**Comment by michield** [comment]
Have you tested that on all devices? The main reason for 15 is small screens.

**Comment by samtuke** [comment]
@michield Yes, on small screens the address wraps over two lines for long addresses, which takes up otherwise empty space, as the date and stats also wrap.

selection_319
selection_318

**Comment by bramley** [comment]
Might be able to reduce the width of the response field by using abbreviated labels for day, minute etc
image

**Comment by samtuke** [comment]
@bramley Ideally this would be handled client-side by JS so that full labels are displayed when space is available, and not when not. Otherwise we would use potentially confusing abbreviations in all cases. I don't think d, m, s are sufficiently clear to use in all cases.

**Comment by bramley** [comment]
OK, but I expected the abbreviations to be language-specific. In English I think that 1d 2h 3m 4s is reasonably clear.

Currently something like 20 hours 58 minutes 21 seconds seems unnecessarily verbose and, as in your screenshot, can cause wrapping over three lines making it a bit harder to read.

**Comment by samtuke** [comment]
@bramley If the first label was always fully printed, then others could be abbreviated with less loss of clarity. 

E.g.:
1 day 15 h 25 m 6 s
6 hours 3 m 58 s

It seems that PHP date functions don't provide a way to do this, but a custom function to achieve it would probably be overkill.

Another way to shorten it would be to only include seconds (both value and label) if the duration is less than one day (the assumption being that seconds are irrelevant for long time frames like that). What do you think?

**Comment by bramley** [comment]
Sam, continuing the discussion of formatting the response time is likely to delay this pull request, so I suggest starting a new issue. My original intention was only to reduce the space taken by the response time in order to give more space for the email address, not really to find the best way to format the response time.

**Comment by samtuke** [comment]
@bramley Agreed
@michield Please review and merge without waiting for any further changes

**Pull request merged**
