### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by adgitate1**
Fix link

### CODE REVIEW

**Comment by michield** [comment]
To accept this PR, would you mind signing the [CLA](https://www.phplist.com/cla)? Thanks

**Comment by adgitate1** [comment]
It is now signed.

**Comment by adgitate1** [comment]
Side question: Do you know if phplist.com's source is publicly hosted? The meta tag in the header of the CLA page has charset=ISO-8859-1 encoding so I'm seeing a lot of "â€œ". I'd like to do a pull request to change it to "utf-8". (to be consistent with their other pages e.g. https://www.phplist.com/terms )

**Comment by michield** [comment]
Thanks. I'll check the charset on that page. It's indeed wrong. Thanks.

**Pull request merged**
