### PR TITLE
Added phpList config file to .gitignore

### PR DESCRIPTION
**Pull request by samtuke**

### CODE REVIEW

**Comment by bramley** [comment]
What is the idea behind this? Adding to .gitignore means that the initial config file won't be in the repository. Is there some other way of including a config file in the released package?

**Comment by samtuke** [comment]
@bramley The aim is to avoid accidentally committing local changes to this file, which happens from time to time in my own and other developers' work.

Because the file is already committed, it does not mean that the file won't be distributed; the current version is unaffected by this change. However it does mean that future changes to this file can only be committed by using -f flag to 'force' commit (overriding .gitignore). The result should be that it is harder to commit changes by mistake, but still possible to to force changes on the rare occasions that it is necessary.

Do you agree?

**Comment by bramley** [comment]
Doesn't that make it more difficult to commit genuine changes to the file?

**Comment by michield** [comment]
You should use the "SetEnv /path/to/config.php" in your Apache config and not use the config that is on the repository for your local system.

**Comment by michield** [comment]
See https://resources.phplist.com/develop/developmentsetup

**Comment by samtuke** [comment]
@bramley Yes it does, which is the point. Only deliberate changes should be made to that file in any case; recently the rate of change has been approximately two commits per year. On the other hand not having it ignored requires stashing and popping changes several times each day in order to avoid committing the changes by mistake.

**Comment by samtuke** [comment]
@michield
> You should use the "SetEnv /path/to/config.php" in your Apache config and not use the config that is on the repository for your local system.

I do for some servers, but this additional step inevitably gets missed in some environment setups. Having to use a git flag at most twice per year to avoid a daily risk with diverse environments and developers and avoid an additional web server initialisation step is worth the inconvenience in my view.

**Comment by michield** [comment]
Can't merge this

**Pull request closed without merging**
