### PR TITLE
Feature to receive deletebounce for debugging rule

### PR DESCRIPTION
**Pull request by jd440**
I got a problem with a bad rule, deleting bounce, (which i don't),
This help me to find the bad rule.

### CODE REVIEW

**Comment by bramley** [comment]
As this change is reporting deleted bounces then the name of the setting should be REPORT_DELETED_BOUNCES.  Any "debug" output would go somewhere else, such as to a log file to just displayed on the page.

**Comment by jd440** [comment]
Let me know if there is anything else!

**Comment by jd440** [comment]
what's up?

**Comment by samtuke** [comment]
@bramley Any further comments?

**Comment by bramley** [comment]
Only two smalls point about config_extended.php.
Ideally the value of REPORT_DELETED_BOUNCES should match that in init.php, so that someone can swap config.php with config_extended.php.
Also the comment could be clearer, maybe something like

`// Set to 1 to include bounce deletions in the advanced bounce processing report`
define('REPORT_DELETED_BOUNCES', 0);

**Comment by jd440** [comment]
thanks @bramley Done!

**Pull request merged**
