### PR TITLE
Display list names on the messages page

### PR DESCRIPTION
**Pull request by bramley**
Display the names of the lists to which a campaign has been or will be sent.

I have added a row to show the list names but there might be a better way of doing that. To avoid the "Lists" label, maybe append the list names to the campaign subject

image

### CODE REVIEW

**Comment by suelaP** [comment]
Why do you think it is necessary to add that there when the information is already available when clicking the "View" campaign option?

**Comment by bramley** [comment]
The benefit is seeing immediately the lists to which the campaign was sent or will be sent.

This arose because a client of mine composed a campaign and chose the wrong list. Looking at the Active tab of the messages page for confirmation he saw that it was scheduled to be sent but did not see that he had chosen the wrong list. Possibly the list names could be displayed only on the Active tab but I don't see a problem displaying on all the tabs.

**Comment by michield** [comment]
It works when there is only one or a small number of lists, but what happens if the amount of lists is large?

**Comment by suelaP** [comment]
Yes, that's my concern too. I have seen very long list names too. 
Also, I think adding this will put too much information on one page, making it as a whole less readable.

**Comment by samtuke** [comment]
What about showing the lists only for active campaigns? Some users also have many campaign running simultaneously, I suppose, but still it would solve the visual clutter problem on the other tabs.

**Comment by bramley** [comment]
Perhaps display only a few list names with an indication of how many other lists were sent to. 

This example displays a maximum of three lists. If there are more than three then only the first two are displayed with an indication of the number not being shown.
image

I'm not sure about long list names, possibly truncate to a length that will display reasonably in both themes. Is there anywhere else that list names are truncated?

**Comment by michield** [comment]
Yes, that's quite nice, I think that would work. Even with long names, it wouldn't be too bad. It would probably be good if the "and 2 more" links to the place where this is expanded.

**Comment by bramley** [comment]
Now made the "and n more" a link to the lists on the view message page
image

**Comment by michield** [comment]
Great!

**Comment by suelaP** [comment]
@bramley  I don't know if it was intentional but these changes are applied for sent campaigns too, not only those on the active tab. I thought we agreed on Sam's proposal to only do that for campaigns being sent ( as in that way it would address the problem you described earlier in the thread). @xh3n1  can work on reverting the commit related to the sent tab, but maybe you want to make the change yourself?

**Comment by bramley** [comment]
> I thought we agreed on Sam's proposal to only do that for campaigns being sent

No, there wasn't any further discussion of the suggestion to limit the change to only the Active tab. 

The vertical impact of the change is limited by displaying only three list names. Can you show a  screenshot where that is too disruptive?

**Comment by suelaP** [comment]
@bramley I agree that isn’t too distruptive but, I can’t see any value on adding it there either. The problem you described is resolved with adding the lists on campaigns being sent. As per already sent campaigns the information is already there and easy accessible.

**Comment by xh3n1** [comment]
Maybe we should revert the commit for the release branch and keep it on master for changes if needed?  What do you think?

**Comment by suelaP** [comment]
I agree @xh3n1

**Comment by michield** [comment]
I don't see a value in reverting. It's not obstructing anything, and reverting will increase the work involved, having to re-check it. For now, we should close this and leave it as is.

**Pull request merged**
