### PR TITLE
return error code on FAIL in ajax subscribe

### PR DESCRIPTION
**Pull request by maltfield**
See bug report (quoted below link)

 * https://mantis.phplist.org/view.php?id=19524

> This is apparently a long-standing issue with the community-recommended way for users to be able to add subscribers to phplist from an external domain using ajax in phplist3 as described in this thread:
> 
>  * https://discuss.phplist.org/t/ajax-subscribe-api/974
> 
> The code in the zip file attached to the above thread uses jquery's ajax function, and it defines a function success() that's triggered when the ajax call succeeds and a error() function that's triggered when the ajax call failed. The problem is: phplist merely prints "FAIL" in the response when the subscribe attempt fails, but the status code remains a 200.
> 
> IMHO, the ajax form should not have to search for the string "FAIL" in the response in order to detect a failure. Instead, it should check the status code of the HTTP response from the server. This can be achieved, for example, by throwing an exception in PHP--which will make PHP return a 500 Internal Server Error.
> 
> Here is the relevant code for handling ajax subscription queries on phplist's side:
> 
>  * https://github.com/phpList/phplist3/blob/7ec8ab78f215894c29da8e54ff9d7c41ffde64c6/public_html/lists/index.php#L242-L272
> 
> My recommendation is to add the line:
> 
>     throw new Exception( "Error: Subscribe attempt failed!" );
> 
> after the "echo 'FAIL';" line here:
> 
>  * https://github.com/phpList/phplist3/blob/7ec8ab78f215894c29da8e54ff9d7c41ffde64c6/public_html/lists/index.php#L270

### CODE REVIEW

**Comment by michield** [comment]
:+1:

**Comment by bramley** [comment]
This change doesn't appear to have the expected outcome, causing a 500 error to be returned. 

`                     throw new Exception( "Error: Subscribe attempt failed!" ); `

In my test the status was still 200. 
image
The web server is running LiteSpeed, so whether an unhandled php exception causes a server error might be dependent on the environment. The usual way of returning a specific status code though is the header() function.
But returning 500 for the case of someone already subscribed seems a bit excessive.

A better solution would be to have a configurable message that is returned, similar to that for a successful request
image
Then the client doesn't need to know whether the subscription was successful or not. It just displays the returned text.

**Comment by maltfield** [comment]
@bramley this definitely returns 500 on our setup with an apache backend. I wonder if the difference in your environment is your php config or web server (LiteSpeed).

I thought about setting the header--which would be the most exact way to achieve this desired result (and I do believe it's a must that the return code to be non-200 on error), but I intentionally avoided that solution since--iirc--calling header() must be done before any output is sent, and could therefore break things either as they are now or in the future.

**Comment by maltfield** [comment]
@bramley did you test this in dev or production? Try setting display_errors to 0 in your php config and see if it's still returning a 200. Production, of course, should have display_errors set to off.

Per https://www.reddit.com/r/PHP/comments/4iubg1/why_doesnt_php_send_a_500_status_code_if_an/

**Comment by maltfield** [comment]
Another possible option would be to use http_response_code(), which--at least from the documentation--looks like it might not have the same "must call before output" limitations as header()

 * https://secure.php.net/manual/en/function.http-response-code.php

**Comment by bramley** [comment]
The site is shared hosting so is quite restricted in changing the php configuration, but display_errors is off.

phplist starts output buffering at the start of index.php, so header() would be ok (which is how I tested it previously when the exception did not have the desired effect) but http_response_code() should be ok too.

**Comment by michield** [comment]
Yes, it should be ok to use header()

**Pull request merged**
