### PR TITLE
fix shortenTextDisplay function

### PR DESCRIPTION
**Pull request by mikhailnk**
Fixed shortening function (mb_str*)

### CODE REVIEW

**Comment by michield** [comment]
It would be good to add a test on the availability of the mb_ functions. They are not alwasy there.

**Comment by michield** [comment]
instead of this PR, I added a check to make sure the mb_ functions exist.

https://github.com/phpList/phplist3/commit/932f911b232bf650d3703c13b8772caa9a58e373

**Comment by mikhailnk** [comment]
The same test should be added to other files (or add to the requirements for hosting):
admin/commonlib/lib/interfacelib.php
admin/connect.php
admin/index.php
admin/PHPMailer/class.phpmailer.php (!)

**Comment by michield** [comment]
phpMailer has the tests. The others are all mb_strtolower which is dealt with (not very elegantly) here https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L19

**Pull request closed without merging**
