### PR TITLE
Support [CONTACTURL] placeholder

### PR DESCRIPTION
**Pull request by xh3n1**
## Related Issue
https://mantis.phplist.org/view.php?id=19882

### CODE REVIEW

**Comment by samtuke** [comment]
@bramley Does this look OK to you?

**Comment by bramley** [comment]
htmlspecialchars() is sufficient to escape html, no need to use htmlentities(). This is consistent with use elsewhere in this file, e.g.

    $html['preferencesurl'] = sprintf('%s%suid=%s', $url, htmlspecialchars($sep), $hash);


The text value should not be encoded.

**Comment by samtuke** [comment]
@bramley Thanks!

**Comment by suelaP** [comment]
@xh3n1 Can you please check?

**Comment by xh3n1** [comment]
@suelaP sure, both work for me. I prefer using htmlentities() wherever I can since it's a better security practice, but for this particular case, htmlspecialchars() works also fine.

**Pull request merged**
