### PR TITLE
Changed page title to use campaign title (not subject)

### PR DESCRIPTION
**Pull request by samtuke**
- Changed page title to use campaign title (not subject); 
- Added campaign 'subject' to data table; 
- Added date formatting

### CODE REVIEW

**Comment by michield** [comment]
can you explain what this does?

**Comment by samtuke** [comment]
It uses the campaign title instead of the campaign subject as the page title. The campaign title may be the same or different to the subject. If it is different, then the campaign subject is not printed anywhere on the page (only the campaign title is). Therefore the campaign subject is printed separately in the table to avoid any ambiguity.

**Comment by bramley** [comment]
The calls to formatDateTime for the embargo, finish sending, repeat until, and requeue until fields are incorrect. They display just the current date/time, not the message field.

**Comment by samtuke** [comment]
@bramley Great catch -- this should be fixed in https://github.com/phpList/phplist3/pull/173

**Pull request merged**
