### PR TITLE
fix saving the password when editing a subscriber

### PR DESCRIPTION
**Pull request by michield**
As found in #791 

The password when editing a subscriber wasn't saved.

This change does the following:

- only display the password field when "ASKFORPASSWORD" is true (which is not default)
- save the password correctly when entered
- remove sys: in front of the password field (cosmetic)

### CODE REVIEW

**Comment by michield** [comment]
@gabrielfin @bramley can you check and comment? I tested it, and it seems to work fine.

1. create a user
2. set a password
3. login with the password on the subscribe page

you need to set **define('ASKFORPASSWORD',true)** in the config file

**Comment by bramley** [comment]
On the Subscriber Profile page the password field and the last time changed need to be displayed together and updated together. Currently when ASKFORPASSWORD is false the last time changed is still displayed, and entering a new password doesn't update the time last changed.

Also, and it puzzled me for a bit, the current password is not displayed so the caption is a bit misleading. Maybe change it to "Enter new password".
I will push my local commit with these changes for you to look at.

**Comment by gabrielfin** [comment]
The `autocomplete="new-password"` part seems to be working correctly.

**Comment by michield** [comment]
> On the Subscriber Profile page the password field and the last time changed need to be displayed together and updated together. Currently when ASKFORPASSWORD is false the last time changed is still displayed, and entering a new password doesn't update the time last changed.

Good point.

> 
> Also, and it puzzled me for a bit, the current password is not displayed so the caption is a bit misleading. Maybe change it to "Enter new password".

Yes, but let's leave that for now. Changing the label may have an impact in other places. This is not common functionality, so it's not a big issue.

> I will push my local commit with these changes for you to look at.

Yes, great, that looks good.

**Comment by michield** [comment]
> The `autocomplete="new-password"` part seems to be working correctly.

Thanks for confirming. Can you give the steps to test that?

**Comment by michield** [comment]
> > Also, and it puzzled me for a bit, the current password is not displayed so the caption is a bit misleading. Maybe change it to "Enter new password".
> 
> Yes, but let's leave that for now. Changing the label may have an impact in other places. This is not common functionality, so it's not a big issue.
> 
Ah, you did include that. Yes, that'll work.

Tested, and works all fine. Thanks

**Comment by gabrielfin** [comment]
> Thanks for confirming. Can you give the steps to test that?

This happens with Bitwarden and its browser extension. Although I'm not sure if it happens with other password managers or even Firefox's or Chrome's, because in this specific case, the input is of type `text` and not `password`, which is not common for login forms. But Bitwarden autofills password inputs even if they're of type `text`. I don't know if any other password manager does that as well.

To reproduce, you need to:
- have a Bitwarden account
- have the Bitwarden extension
- have a login entry stored for the administrator user for your PHPList instance
- check the option in Bitwarden: Settings > Options > Enable auto-fill on page load
- whenever you edit a subscriber, your administrator password is (was) autofilled into the subscriber's password field

If you submit the form without noticing that, it will lead to the subscriber's password being overwritten with the administrator password. And it would also reveal your administrator password to anyone looking at your screen.

**Pull request merged**
