### PR TITLE
Add http to vCard url

### PR DESCRIPTION
**Pull request by xh3n1**
## Related Issue

https://mantis.phplist.org/view.php?id=19883

### CODE REVIEW

**Comment by samtuke** [comment]
Looks like this also hyphenates the filename of the vcard

**Comment by bramley** [comment]
@xh3n1 @samtuke  This shouldn't use simply "http". There is a global variable `$public_scheme` that has the correct protocol. There is also a global for the website, `$website`

As an example see this code that constructs the click tracking links

        $newlink = sprintf('<a %shref="%s://%s/lt.php?tid=%s" %s>%s</a>', $links[1][$i],
            $GLOBALS['public_scheme'], $website.$GLOBALS['pageroot'], $masked, $links[4][$i],
            $links[5][$i]);

**Comment by samtuke** [comment]
@bramley Thanks. Using `$website` would save executing another database query, which is good. Why use `$public_scheme` though? Isn't that the protocol for accessing the phpList installation itself? We expect the website URL to be hosted independently of the phpList installation.

**Comment by bramley** [comment]
Sorry, I misunderstood slightly what is being changed. yes `$public_scheme` is for the phplist public pages e.g. the `https` in `https://mysite.com/lists`

But `$website` is just the domain for phplist, `mysite.com` in the above URL. I don't think that it was intended to be the domain for other uses. People might want to use a different domain for the vcard contact information, for example if phplist is installed on a sub-domain, so using `$website` is just a best-guess, unless you add another configuration field.

**Comment by samtuke** [comment]
@bramley Yes it's unclear where is best to link to for the vcard URL field. We wanted to avoid adding a new config field if possible. The current implemtation assumes that there is an accessible website on the domain of the phpList installation. There may not be. Alternatively we could link to the default public page, which should be accessible, and at least contains contact info for the phpList installation admin and an overview of public lists (potentially useful), if nothing else. Thoughts?

**Pull request merged**
