### PR TITLE
add setting PHPMAILERSUBSCRIBEHOST to be used for subscribe page mails

### PR DESCRIPTION
**Pull request by michield**
## Description
Allow setting up a different SMTP host for the messages that originate from the subscribe pages.

## Docs
https://resources.phplist.com/system/config/phpmailersubscribehost

### CODE REVIEW

**Comment by michield** [comment]
@bramley do you see any issues with this?

I'm trying to create a new flag to use for mails that are generated from subscribe pages. Currently they would use the PHPMAILERTESTHOST if defined or PHPMAILERHOST instead.

I didn't bother to add auth vars for it. At some point it could be useful to redefine the relay system anyway, and have an array of hosts that can be identified for various purposes, but for now this is a quick update to split out the subscription related emails.

**Comment by bramley** [comment]
I take it that the new setting will be used for emails sent when changing preferences, unsubscribing, and forwarding, in addition to subscribing.

The code changes look ok, but can be simplified a bit. In init.php most of the constants are defined with a default value, so there is no need to test again whether they are defined in phplistmailer.php.

**Comment by michield** [comment]
> I take it that the new setting will be used for emails sent when changing preferences, unsubscribing, and forwarding, in addition to subscribing.

Yes. that's the idea. Any mails generated from subscription related actions.

> 
> The code changes look ok, but can be simplified a bit. In init.php most of the constants are defined with a default value, so there is no need to test again whether they are defined in phplistmailer.php.

Yes, fair enough. It's kind of a habit to write it like that. I don't think it matters really.

> 
> You might want to consider what should happen when phplist is run from a cron job.

At the moment cronjobs should not create subscription related mails, but they may in the future. I was thinking at some point to add a "reminder" cron, for sending the request for confirmation a few days after sign up (when not confirmed). But we can check once that's done.

Thanks, I'll mark it ready for now.

**Comment by bramley** [comment]
> Any mails generated from subscription related actions.

It is going to include other emails, such as admin reports produced when processing the queue.

        } elseif (!$this->inBlast && empty($_SESSION['adminloggedin']) && 

I think that $_SESSION['adminloggedin'] is empty when in a cron job but not when processing the queue in the browser.

**Comment by michield** [comment]
Ah, yes, quite possibly. But that's kind of a nice side effect. The aim is to make this IP more deliverable.

**Pull request merged**
